import {useState} from 'react';
import {ArrowRight,BookOpen,CalendarDays,CheckCircle2,Facebook,GraduationCap,MapPin,Menu,MessageCircle,Phone,Send,Users,X,Sparkles} from 'lucide-react';
import './tieng-trung.css';
const courses=[['HSK 1–9','Lộ trình 4 kỹ năng từ số 0 đến nâng cao',GraduationCap],['Tiếng Trung giao tiếp','Phản xạ và tình huống thực tế',MessageCircle],['Tiếng Trung trẻ em','Học qua hình ảnh, trò chơi và hội thoại',Users],['Tiếng Trung người đi làm','Văn phòng, nhà máy và thương mại',BookOpen],['Luyện thi HSK','Ôn tập và thi thử theo mục tiêu',CheckCircle2],['Du học & định hướng','Tiếng Trung gắn với học tập và nghề nghiệp',Sparkles]];
const levels=['HSK 0','HSK 1','HSK 2','HSK 3','HSK 4','HSK 5','HSK 6','HSK 7–9'];
export default function TiengTrungLienHoa(){const[menu,setMenu]=useState(false),[sent,setSent]=useState(false);const go=(id:string)=>{document.getElementById(id)?.scrollIntoView({behavior:'smooth'});setMenu(false)};return <div className="lh-page">
<header><button className="brand" onClick={()=>go('home')}><span className="mark">聯</span><span><b>TIẾNG TRUNG LIÊN HOA</b><small>LIÊN HOA GLOBAL EDUCATION</small></span></button><nav className={menu?'open':''}><button onClick={()=>go('courses')}>Khóa học</button><button onClick={()=>go('hsk')}>HSK 1–9</button><button onClick={()=>go('kids')}>Trẻ em</button><button onClick={()=>go('schedule')}>Khai giảng</button><button onClick={()=>go('register')}>Đăng ký tư vấn</button></nav><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
<section id="home" className="hero"><div><span className="eyebrow">HỆ THỐNG ĐÀO TẠO TIẾNG TRUNG</span><h1>Học tiếng Trung <em>đúng lộ trình</em>.<br/>Tự tin giao tiếp. Chinh phục HSK.</h1><p>Lộ trình từ số 0 đến HSK 9, giao tiếp, trẻ em và tiếng Trung định hướng nghề nghiệp.</p><div className="actions"><button className="primary" onClick={()=>go('hsk')}>Xem lộ trình <ArrowRight/></button><button className="secondary" onClick={()=>go('register')}>Đăng ký tư vấn</button></div><div className="proof"><b>HSK 1–9<small>Lộ trình đầy đủ</small></b><b>4 KỸ NĂNG<small>Nghe · Nói · Đọc · Viết</small></b><b>2 CƠ SỞ<small>Bắc Ninh · Lạng Sơn</small></b></div></div><div className="hero-art"><div className="seal">學</div><div className="card a">今日中文<strong>你好！</strong><small>Nǐ hǎo · Xin chào</small></div><div className="card b">HSK<strong>1 → 9</strong><small>Chinh phục từng cấp độ</small></div><div className="mountain"/></div></section>
<div className="strip"><b>中文</b><span>Học tiếng Trung để mở rộng cơ hội học tập, nghề nghiệp và kết nối.</span><b>你好</b><b>HSK</b></div>
<section id="courses" className="section"><div className="heading"><div><span className="eyebrow">CHƯƠNG TRÌNH ĐÀO TẠO</span><h2>Một nơi cho mọi mục tiêu tiếng Trung</h2></div><p>Từ người mới bắt đầu đến người cần chứng chỉ HSK hoặc tiếng Trung phục vụ công việc.</p></div><div className="grid">{courses.map(([title,text,Icon])=><article className="course" key={String(title)}><div className="icon"><Icon/></div><h3>{title}</h3><p>{text}</p><button onClick={()=>go('register')}>Tìm hiểu <ArrowRight/></button></article>)}</div></section>
<section id="hsk" className="section hsk"><div className="heading"><div><span className="eyebrow">LỘ TRÌNH HSK 3.0</span><h2>Từ số 0 đến HSK 9</h2></div><p>Chia nhỏ mục tiêu để học viên biết mình đang ở đâu và bước tiếp theo là gì.</p></div><div className="levels">{levels.map((x,i)=><div key={x}><span>{i+1}</span><b>{x}</b><small>{i<2?'Nền tảng':i<5?'Phát triển':'Nâng cao'}</small></div>)}</div><div className="skills"><span>听 Nghe</span><span>说 Nói</span><span>读 Đọc</span><span>写 Viết</span><span>词汇 Từ vựng</span></div></section>
<section id="kids" className="section kids"><div><span className="eyebrow">TIẾNG TRUNG TRẺ EM</span><h2>Cho trẻ làm quen tiếng Trung bằng niềm vui học tập</h2><p>Phát âm, từ vựng, hội thoại và chữ Hán thông qua hình ảnh và tương tác.</p><div className="ages"><b>5–7 <small>Làm quen âm thanh & từ vựng</small></b><b>8–10 <small>Hội thoại & phản xạ</small></b><b>11–14 <small>Đọc hiểu & nền tảng HSK</small></b></div><button className="primary" onClick={()=>go('register')}>Tư vấn lớp trẻ em <ArrowRight/></button></div><div className="kids-art">熊猫<div>你好！<small>Nǐ hǎo!</small></div></div></section>
<section id="schedule" className="section"><div className="heading"><div><span className="eyebrow">LỊCH KHAI GIẢNG</span><h2>Chọn lớp phù hợp</h2></div><p>Lịch mẫu – liên hệ để xác nhận lịch thực tế.</p></div><div className="schedule">{['HSK · Online','Giao tiếp · Bắc Ninh','Trẻ em · Lạng Sơn'].map(x=><article key={x}><CalendarDays/><div><b>{x}</b><small>Lịch mẫu – liên hệ xác nhận</small></div><button onClick={()=>go('register')}>Đăng ký <ArrowRight/></button></article>)}</div></section>
<section className="why"><div><span className="eyebrow">VÌ SAO LIÊN HOA</span><h2>Học có lộ trình. Tiến bộ có thể theo dõi.</h2></div><div className="whygrid">{['Lộ trình rõ ràng','Thực hành giao tiếp','Theo sát tiến độ','Luyện HSK và thi thử','Online hoặc trực tiếp','Định hướng nghề nghiệp'].map(x=><div key={x}><CheckCircle2/>{x}</div>)}</div></section>
<section id="register" className="section register"><div className="register-card"><div><span className="eyebrow">ĐĂNG KÝ TƯ VẤN</span><h2>Bắt đầu lộ trình tiếng Trung của bạn</h2><p>Để lại thông tin để Liên Hoa tư vấn chương trình phù hợp.</p><p><MapPin/> Bắc Ninh · Lạng Sơn</p><p><Phone/> Điện thoại · Zalo · Messenger</p></div>{sent?<div className="success"><CheckCircle2/><h3>Đã nhận thông tin!</h3><p>Liên Hoa sẽ liên hệ lại.</p></div>:<form onSubmit={e=>{e.preventDefault();setSent(true)}}><input required placeholder="Họ và tên"/><input required placeholder="Số điện thoại"/><select><option>Bắc Ninh</option><option>Lạng Sơn</option><option>Online</option></select><select><option>HSK 1–9</option><option>Giao tiếp</option><option>Trẻ em</option><option>Người đi làm</option></select><textarea placeholder="Mục tiêu học / nội dung cần tư vấn"/><button className="primary">Gửi đăng ký <Send/></button></form>}</div></section>
<footer><div className="brand"><span className="mark">聯</span><span><b>TIẾNG TRUNG LIÊN HOA</b><small>LIÊN HOA GLOBAL EDUCATION</small></span></div><p>Học tiếng Trung thực chiến – HSK – Giao tiếp – Trẻ em – Định hướng nghề nghiệp.</p></footer><div className="float"><button><MessageCircle/></button><button><Facebook/></button><button><Phone/></button></div></div>}
