import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Users, UserRound, Bell, DollarSign, CheckCircle2, LogOut, Plus, Search, UserCog, RefreshCw, ShieldCheck, UserPlus, Power, X, KeyRound, Phone, MessageSquare, CalendarClock, LayoutDashboard, Inbox, Building2, Filter, Clock, Save, ChevronRight, FileText, CircleDot, Loader2 } from 'lucide-react';
import { supabase } from './lib/supabase';
import './styles.css';
import './crm.css';

type Role = 'director' | 'admin' | 'sale';
type Profile = { id:string; full_name:string; email:string|null; role:Role; branch:string|null; active:boolean; created_at?:string };
type Lead = { id:string; full_name:string; phone:string|null; email?:string|null; course:string|null; source:string; branch:string|null; status:string; assigned_to:string|null; notes:string|null; next_follow_up:string|null; created_at:string; updated_at?:string; assignee?:{full_name:string}|null };
type Activity = { id:string; lead_id:string; actor_id:string; activity_type:string; content:string|null; created_at:string };
type FollowUp = { id:string; lead_id:string; assigned_to:string; due_at:string; status:string; note:string|null; created_at:string };

const statuses = { new:'Mới', consulting:'Đang tư vấn', interested:'Đã quan tâm', follow_up:'Chờ follow-up', closed:'Đã chốt', lost:'Mất lead' } as Record<string,string>;
const roles = { director:'Giám đốc', admin:'Admin', sale:'Sale' } as Record<Role,string>;
const branches = ['Bắc Ninh','Lạng Sơn'];

function clearRecoveryError(){ if(location.hash.includes('error=') || location.hash.includes('otp_expired')) history.replaceState(null,'',location.pathname+location.search); }

function App(){
 const [session,setSession]=useState<any>(null), [profile,setProfile]=useState<Profile|null>(null), [leads,setLeads]=useState<Lead[]>([]), [staff,setStaff]=useState<Profile[]>([]);
 const [page,setPage]=useState<'dashboard'|'leads'|'staff'>('dashboard'), [query,setQuery]=useState(''), [status,setStatus]=useState('all');
 const [loading,setLoading]=useState(true), [error,setError]=useState(''), [notice,setNotice]=useState('');
 const [showAdd,setShowAdd]=useState(false), [showStaffModal,setShowStaffModal]=useState(false), [resetStaff,setResetStaff]=useState<Profile|null>(null), [selectedLead,setSelectedLead]=useState<Lead|null>(null);
 const [activities,setActivities]=useState<Activity[]>([]), [followups,setFollowups]=useState<FollowUp[]>([]), [activityText,setActivityText]=useState(''), [followDate,setFollowDate]=useState(''), [saving,setSaving]=useState(false);

 useEffect(()=>{ clearRecoveryError(); if(!supabase){setLoading(false);return;} supabase.auth.getSession().then(({data})=>setSession(data.session)); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return ()=>subscription.unsubscribe(); },[]);
 useEffect(()=>{ if(session?.user) loadData(); else if(!supabase) setLoading(false); },[session]);
 async function loadData(){ if(!supabase||!session)return; setLoading(true); setError(''); const [{data:p,error:pe},{data:l,error:le},{data:s,error:se}]=await Promise.all([
  supabase.from('profiles').select('id,full_name,email,role,branch,active,created_at').eq('id',session.user.id).single(),
  supabase.from('leads').select('*,assignee:profiles!leads_assigned_to_fkey(full_name)').order('created_at',{ascending:false}),
  supabase.from('profiles').select('id,full_name,email,role,branch,active,created_at').order('full_name')
 ]); if(pe){setError(pe.message);await supabase.auth.signOut();return;} if(!p?.active){setError('Tài khoản đã bị vô hiệu hóa.');await supabase.auth.signOut();return;} if(le)setError(le.message); if(se)setError(se.message); setProfile(p);setLeads(l||[]);setStaff(s||[]);setLoading(false); }
 async function signOut(){await supabase?.auth.signOut();setProfile(null);}
 const canManage=profile?.role==='director'||profile?.role==='admin';
 const scopedStaff=useMemo(()=>staff.filter(s=>s.active && (profile?.role==='director'||!profile?.branch||s.branch===profile.branch)),[staff,profile]);
 const visible=useMemo(()=>leads.filter(l=>(status==='all'||l.status===status)&&[l.full_name,l.phone,l.email,l.course,l.source,l.branch,l.assignee?.full_name].join(' ').toLowerCase().includes(query.toLowerCase())),[leads,status,query]);
 const metrics={total:leads.length, care:leads.filter(x=>['consulting','interested','follow_up'].includes(x.status)).length, closed:leads.filter(x=>x.status==='closed').length, follow:leads.filter(x=>x.status==='follow_up'||x.next_follow_up).length};
 async function addLead(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase||!session)return;const f=new FormData(e.currentTarget);const branch=String(f.get('branch')||profile?.branch||branches[0]);const assigned=canManage?String(f.get('assigned_to')||''):session.user.id;const {error}=await supabase.from('leads').insert({full_name:f.get('full_name'),phone:f.get('phone'),email:f.get('email'),course:f.get('course'),source:f.get('source')||'manual',branch,notes:f.get('notes'),assigned_to:assigned||null,created_by:session.user.id});if(error)setError(error.message);else{setShowAdd(false);setNotice('Đã thêm Lead.');await loadData();}}
 async function assign(id:string,value:string){if(!supabase)return;const {error}=await supabase.from('leads').update({assigned_to:value||null}).eq('id',id);if(error)setError(error.message);else await loadData();}
 async function updateStatus(id:string,value:string){if(!supabase)return;const {error}=await supabase.from('leads').update({status:value}).eq('id',id);if(error)setError(error.message);else{await addActivity(id,'status_change',`Đổi trạng thái → ${statuses[value]||value}`);await loadData();}}
 async function openLead(l:Lead){setSelectedLead(l);setActivityText('');setFollowDate(l.next_follow_up?new Date(l.next_follow_up).toISOString().slice(0,16):''); if(!supabase)return; const [{data:a,error:ae},{data:f,error:fe}]=await Promise.all([supabase.from('lead_activities').select('*').eq('lead_id',l.id).order('created_at',{ascending:false}),supabase.from('follow_ups').select('*').eq('lead_id',l.id).order('due_at',{ascending:false})]);if(ae||fe)setError((ae||fe)?.message||'');setActivities(a||[]);setFollowups(f||[]);}
 async function addActivity(leadId:string,type:string,content:string){if(!supabase||!session||!content.trim())return;const {error}=await supabase.from('lead_activities').insert({lead_id:leadId,actor_id:session.user.id,activity_type:type,content:content.trim()});if(error)setError(error.message);}
 async function saveNote(){if(!selectedLead||!activityText.trim())return;setSaving(true);await addActivity(selectedLead.id,'note',activityText);setActivityText('');await openLead(selectedLead);setSaving(false);}
 async function saveFollowUp(){if(!supabase||!session||!selectedLead||!followDate)return;setSaving(true);const iso=new Date(followDate).toISOString();const {error}=await supabase.from('follow_ups').insert({lead_id:selectedLead.id,assigned_to:selectedLead.assigned_to||session.user.id,due_at:iso,status:'pending',note:'Follow-up từ CRM'});if(error)setError(error.message);else{await supabase.from('leads').update({next_follow_up:iso,status:'follow_up'}).eq('id',selectedLead.id);await addActivity(selectedLead.id,'follow_up',`Đặt lịch follow-up: ${new Date(iso).toLocaleString('vi-VN')}`);setNotice('Đã đặt lịch follow-up.');await openLead({...selectedLead,next_follow_up:iso,status:'follow_up'});await loadData();}setSaving(false);}
 async function markFollowDone(f:FollowUp){if(!supabase)return;const {error}=await supabase.from('follow_ups').update({status:'done'}).eq('id',f.id);if(error)setError(error.message);else{await addActivity(f.lead_id,'follow_up','Đã hoàn thành follow-up.');if(selectedLead)await openLead(selectedLead);}}
 async function createStaff(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;setError('');const f=new FormData(e.currentTarget);const password=String(f.get('password')||'');if(password.length<8){setError('Mật khẩu tối thiểu 8 ký tự.');return;}const payload={full_name:f.get('full_name'),email:f.get('email'),password,role:f.get('role'),branch:f.get('branch'),active:true};const {data,error}=await supabase.functions.invoke('staff-admin',{body:payload});if(error)setError(error.message);else if(data?.error)setError(data.error);else{setShowStaffModal(false);setNotice('Đã tạo tài khoản nhân viên.');await loadData();}}
 async function toggleStaff(id:string,active:boolean){if(!supabase)return;if(id===session?.user?.id){setError('Không thể vô hiệu hóa tài khoản đang đăng nhập.');return;}const {error}=await supabase.from('profiles').update({active}).eq('id',id);if(error)setError(error.message);else await loadData();}
 async function resetPassword(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase||!resetStaff)return;const f=new FormData(e.currentTarget),password=String(f.get('password')||''),confirm=String(f.get('confirm')||'');if(password.length<8){setError('Mật khẩu tối thiểu 8 ký tự.');return;}if(password!==confirm){setError('Mật khẩu xác nhận không khớp.');return;}const {data,error}=await supabase.functions.invoke('staff-admin',{body:{action:'reset_password',user_id:resetStaff.id,password}});if(error)setError(error.message);else if(data?.error)setError(data.error);else{setResetStaff(null);setNotice('Đã đặt lại mật khẩu nhân viên.');}}
 if(!supabase)return <div className="login"><div className="login-card"><div className="logo big">LH</div><h1>Liên Hoa CRM</h1><p>CRM chưa được cấu hình Supabase.</p></div></div>;
 if(!session)return <Login/>;
 return <div className="app"><aside><div className="brand"><div className="logo">LH</div><div><b>LIÊN HOA</b><small>GLOBAL EDUCATION</small></div></div><nav>
  <Nav active={page==='dashboard'} icon={<LayoutDashboard size={15}/>} text="Dashboard" onClick={()=>setPage('dashboard')}/>
  <Nav active={page==='leads'} icon={<Inbox size={15}/>} text="Inbox / Leads" onClick={()=>setPage('leads')}/><Nav icon={<UserRound size={15}/>} text="Khách hàng"/><Nav icon={<Users size={15}/>} text="Sale & Phân bổ"/><Nav icon={<CalendarClock size={15}/>} text="Follow-up"/><Nav icon={<FileText size={15}/>} text="Khóa học"/><Nav icon={<DollarSign size={15}/>} text="Thu học phí"/><Nav icon={<CheckCircle2 size={15}/>} text="KPI & Báo cáo"/>{canManage&&<Nav active={page==='staff'} icon={<UserCog size={15}/>} text="Quản trị nhân sự" onClick={()=>setPage('staff')}/>} 
 </nav><div className="side-foot"><div className="user"><UserCog size={14}/><span>{profile?.full_name||session.user.email}</span></div><small>{profile?.role?roles[profile.role].toUpperCase():'SALE'} • {profile?.branch||'TOÀN HỆ THỐNG'}</small><button onClick={signOut}><LogOut size={14}/> Đăng xuất</button></div></aside>
 <main><header><div><h1>{page==='dashboard'?'Dashboard':page==='leads'?'Inbox / Leads':'Quản trị nhân sự'}</h1><p>{page==='dashboard'?'Tổng quan hoạt động CRM Liên Hoa':page==='leads'?'Quản lý Lead, phân Sale và chăm sóc khách hàng':'Tạo tài khoản, phân quyền và quản lý nhân viên'}</p></div><div className="header-actions"><button className="icon-btn" onClick={loadData} disabled={loading}><RefreshCw size={17}/></button><button className="notify"><Bell size={18}/><span>3</span></button></div></header>
 {error&&<div className="error">{error}<button onClick={()=>setError('')}><X size={13}/></button></div>}{notice&&<div className="success">{notice}<button onClick={()=>setNotice('')}><X size={13}/></button></div>}
 {page==='dashboard'?<Dashboard metrics={metrics} leads={leads} staff={staff} onLeads={()=>setPage('leads')} onOpenLead={openLead}/>:page==='staff'?<StaffPanel staff={staff} current={session.user.id} role={profile?.role} branch={profile?.branch} onAdd={()=>setShowStaffModal(true)} onToggle={toggleStaff} onReset={setResetStaff}/>:<LeadPage leads={leads} visible={visible} query={query} setQuery={setQuery} status={status} setStatus={setStatus} staff={scopedStaff} canManage={canManage} profile={profile} onAdd={()=>setShowAdd(true)} onAssign={assign} onStatus={updateStatus} onOpen={openLead}/>}</main>
 {showAdd&&<AddLeadModal profile={profile} staff={scopedStaff} canManage={canManage} onClose={()=>setShowAdd(false)} onSubmit={addLead}/>} {showStaffModal&&<StaffModal onClose={()=>setShowStaffModal(false)} onSubmit={createStaff}/>} {resetStaff&&<ResetModal staff={resetStaff} onClose={()=>setResetStaff(null)} onSubmit={resetPassword}/>} {selectedLead&&<LeadModal lead={selectedLead} activities={activities} followups={followups} activityText={activityText} setActivityText={setActivityText} followDate={followDate} setFollowDate={setFollowDate} saving={saving} onClose={()=>setSelectedLead(null)} onNote={saveNote} onFollow={saveFollowUp} onDone={markFollowDone} onCall={async()=>{if(selectedLead.phone){await addActivity(selectedLead.id,'call',`Gọi ${selectedLead.phone}`);window.location.href=`tel:${selectedLead.phone}`;}}}/>}</div>;
}

function Nav({active,icon,text,onClick}:{active?:boolean;icon:React.ReactNode;text:string;onClick?:()=>void}){return <a className={active?'active':''} onClick={onClick}>{icon}{text}</a>}
function Card({icon,label,value,note}:{icon:React.ReactNode;label:string;value:string|number;note:string}){return <div className="card"><div className="card-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{note}</small></div></div>}
function Dashboard({metrics,leads,staff,onLeads,onOpenLead}:{metrics:any;leads:Lead[];staff:Profile[];onLeads:()=>void;onOpenLead:(l:Lead)=>void}){const recent=leads.slice(0,6);return <><section className="cards"><Card icon={<Users/>} label="Tổng Lead" value={metrics.total} note="Theo quyền truy cập"/><Card icon={<UserRound/>} label="Đang chăm sóc" value={metrics.care} note="Tư vấn / quan tâm / follow-up"/><Card icon={<CheckCircle2/>} label="Đã chốt" value={metrics.closed} note="Lead đã chốt"/><Card icon={<CalendarClock/>} label="Cần follow-up" value={metrics.follow} note="Cần xử lý"/></section><div className="dashboard-grid"><section className="panel"><div className="panel-head"><div><h2>Lead mới nhất</h2><p>6 Lead gần đây</p></div><button className="primary" onClick={onLeads}>Xem tất cả <ChevronRight size={15}/></button></div><div className="table-wrap"><table><thead><tr><th>Khách hàng</th><th>Nhu cầu</th><th>Cơ sở</th><th>Trạng thái</th></tr></thead><tbody>{recent.map(l=><tr key={l.id} onClick={()=>onOpenLead(l)} className="clickable"><td><b>{l.full_name}</b><small>{l.phone||'Chưa có SĐT'}</small></td><td>{l.course||'—'}</td><td>{l.branch||'—'}</td><td><span className="status-dot"><CircleDot size={12}/>{statuses[l.status]||l.status}</span></td></tr>)}{!recent.length&&<tr><td colSpan={4}>Chưa có Lead.</td></tr>}</tbody></table></div></section><section className="panel"><div className="panel-head"><div><h2>Nhân sự</h2><p>Trạng thái tài khoản</p></div></div><div className="staff-mini">{staff.slice(0,8).map(s=><div key={s.id}><div className="avatar">{s.full_name.slice(0,1).toUpperCase()}</div><div><b>{s.full_name}</b><small>{roles[s.role]} • {s.branch||'Toàn hệ thống'}</small></div><span className={s.active?'pill on':'pill off'}>{s.active?'Hoạt động':'Tắt'}</span></div>)}</div></section></div></>}

function LeadPage({leads,visible,query,setQuery,status,setStatus,staff,canManage,profile,onAdd,onAssign,onStatus,onOpen}:{leads:Lead[];visible:Lead[];query:string;setQuery:(v:string)=>void;status:string;setStatus:(v:string)=>void;staff:Profile[];canManage:boolean;profile:Profile|null;onAdd:()=>void;onAssign:(id:string,v:string)=>void;onStatus:(id:string,v:string)=>void;onOpen:(l:Lead)=>void}){return <section className="panel"><div className="panel-head"><div><h2>Danh sách Lead</h2><p>{visible.length} Lead đang hiển thị • Tổng {leads.length}</p></div><button className="primary" onClick={onAdd}><Plus size={15}/> Thêm Lead</button></div><div className="filters"><div className="search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm tên, SĐT, email, khóa học..."/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Tất cả trạng thái</option>{Object.entries(statuses).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><div className="filter-label"><Filter size={14}/> {profile?.branch||'Toàn hệ thống'}</div></div><div className="table-wrap"><table><thead><tr><th>Khách hàng</th><th>Nhu cầu</th><th>Nguồn / Cơ sở</th><th>Sale phụ trách</th><th>Trạng thái</th><th>Follow-up</th></tr></thead><tbody>{visible.map(l=><tr key={l.id} className="clickable" onClick={()=>onOpen(l)}><td><b>{l.full_name}</b><small>{l.phone||l.email||'Chưa có liên hệ'}</small></td><td>{l.course||'—'}</td><td>{l.source}<small>{l.branch||'—'}</small></td><td onClick={e=>e.stopPropagation()}>{canManage?<select className="inline" value={l.assigned_to||''} onChange={e=>onAssign(l.id,e.target.value)}><option value="">Chưa phân</option>{staff.filter(s=>s.role==='sale').map(s=><option key={s.id} value={s.id}>{s.full_name}</option>)}</select>:<span>{l.assignee?.full_name||'Chưa phân'}</span>}</td><td onClick={e=>e.stopPropagation()}><select className="inline" value={l.status} onChange={e=>onStatus(l.id,e.target.value)}>{Object.entries(statuses).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></td><td>{l.next_follow_up?new Date(l.next_follow_up).toLocaleString('vi-VN'):'Chưa đặt'}</td></tr>)}{!visible.length&&<tr><td colSpan={6}>Không có Lead phù hợp.</td></tr>}</tbody></table></div></section>}

function AddLeadModal({profile,staff,canManage,onClose,onSubmit}:{profile:Profile|null;staff:Profile[];canManage:boolean;onClose:()=>void;onSubmit:(e:React.FormEvent<HTMLFormElement>)=>void}){return <div className="modal-backdrop"><form className="modal wide" onSubmit={onSubmit}><div className="modal-title"><div><h2>Thêm Lead mới</h2><p>Nhập thông tin khách hàng và nhu cầu</p></div><button type="button" onClick={onClose}><X/></button></div><div className="form-grid"><input name="full_name" required placeholder="Họ và tên *"/><input name="phone" placeholder="Số điện thoại"/><input name="email" type="email" placeholder="Email"/><input name="course" placeholder="Khóa học / nhu cầu"/><select name="source"><option>Facebook</option><option>Facebook Ads</option><option>Inbox</option><option>Website</option><option>TikTok</option><option>Giới thiệu</option><option>manual</option></select><select name="branch" defaultValue={profile?.branch||'Lạng Sơn'}>{branches.map(b=><option key={b}>{b}</option>)}</select>{canManage&&<select name="assigned_to" defaultValue=""><option value="">Chưa phân Sale</option>{staff.filter(s=>s.role==='sale').map(s=><option key={s.id} value={s.id}>{s.full_name} • {s.branch}</option>)}</select>}</div><textarea name="notes" placeholder="Ghi chú ban đầu"></textarea><div className="modal-actions"><button type="button" onClick={onClose}>Hủy</button><button className="primary"><Save size={15}/> Lưu Lead</button></div></form></div>}

function LeadModal({lead,activities,followups,activityText,setActivityText,followDate,setFollowDate,saving,onClose,onNote,onFollow,onDone,onCall}:{lead:Lead;activities:Activity[];followups:FollowUp[];activityText:string;setActivityText:(v:string)=>void;followDate:string;setFollowDate:(v:string)=>void;saving:boolean;onClose:()=>void;onNote:()=>void;onFollow:()=>void;onDone:(f:FollowUp)=>void;onCall:()=>void}){return <div className="modal-backdrop"><div className="modal lead-modal"><div className="modal-title"><div><h2>{lead.full_name}</h2><p>{lead.phone||'Chưa có SĐT'} {lead.branch&&`• ${lead.branch}`} {lead.course&&`• ${lead.course}`}</p></div><button onClick={onClose}><X/></button></div><div className="lead-actions"><button onClick={onCall} disabled={!lead.phone}><Phone size={15}/> Gọi điện</button><button disabled={!lead.phone} onClick={()=>lead.phone&&(window.location.href=`sms:${lead.phone}`)}><MessageSquare size={15}/> Nhắn tin</button></div><div className="detail-grid"><section><h3><MessageSquare size={15}/> Nhật ký chăm sóc</h3><textarea value={activityText} onChange={e=>setActivityText(e.target.value)} placeholder="Ghi chú cuộc gọi, nội dung tư vấn, kết quả..."/><button className="primary" onClick={onNote} disabled={saving||!activityText.trim()}>{saving?<Loader2 size={14}/>:<Save size={14}/>} Lưu ghi chú</button><div className="timeline">{activities.map(a=><div key={a.id} className="timeline-item"><div className="timeline-icon"><CircleDot size={12}/></div><div><b>{a.activity_type==='call'?'Cuộc gọi':a.activity_type==='follow_up'?'Follow-up':a.activity_type==='status_change'?'Trạng thái':'Ghi chú'}</b><p>{a.content}</p><small>{new Date(a.created_at).toLocaleString('vi-VN')}</small></div></div>)}{!activities.length&&<p className="muted">Chưa có hoạt động.</p>}</div></section><section><h3><CalendarClock size={15}/> Lịch follow-up</h3><div className="follow-form"><input type="datetime-local" value={followDate} onChange={e=>setFollowDate(e.target.value)}/><button className="primary" onClick={onFollow} disabled={saving||!followDate}><Clock size={14}/> Đặt lịch</button></div><div className="follow-list">{followups.map(f=><div key={f.id} className="follow-item"><div><b>{new Date(f.due_at).toLocaleString('vi-VN')}</b><small>{f.note||'Follow-up'}</small></div>{f.status==='pending'?<button onClick={()=>onDone(f)}>Hoàn thành</button>:<span className="pill on">Đã xong</span>}</div>)}{!followups.length&&<p className="muted">Chưa có lịch follow-up.</p>}</div></section></div></div></div>}

function StaffPanel({staff,current,role,branch,onAdd,onToggle,onReset}:{staff:Profile[];current:string;role:Role|undefined;branch:string|null;onAdd:()=>void;onToggle:(id:string,a:boolean)=>void;onReset:(s:Profile)=>void}){const visible=staff.filter(s=>role==='director'||!branch||s.branch===branch);const active=visible.filter(s=>s.active).length;return <section className="panel"><div className="panel-head"><div><h2>Danh sách nhân viên</h2><p>{visible.length} tài khoản • {active} đang hoạt động {role==='admin'&&branch?`• ${branch}`:''}</p></div><button className="primary" onClick={onAdd}><UserPlus size={15}/> Thêm nhân viên</button></div><div className="staff-summary"><div><ShieldCheck size={17}/><b>Phân quyền</b><span>Giám đốc / Admin / Sale</span></div><div><Building2 size={17}/><b>Cơ sở</b><span>{role==='director'?'Bắc Ninh / Lạng Sơn':branch||'Toàn hệ thống'}</span></div></div><div className="staff-table">{visible.map(s=><div className="staff-row" key={s.id}><div className="avatar">{s.full_name.slice(0,1).toUpperCase()}</div><div className="staff-name"><b>{s.full_name}</b><small>{s.email}</small></div><div><span className="role-pill">{roles[s.role]}</span></div><div>{s.branch||'Toàn hệ thống'}</div><div><span className={s.active?'pill on':'pill off'}>{s.active?'Đang hoạt động':'Đã khóa'}</span></div><div className="staff-actions">{s.id!==current&&<><button onClick={()=>onReset(s)} title="Đặt lại mật khẩu"><KeyRound size={14}/> Đặt lại mật khẩu</button><button onClick={()=>onToggle(s.id,!s.active)} title={s.active?'Khóa tài khoản':'Mở tài khoản'}><Power size={14}/>{s.active?'Khóa':'Mở'}</button></>}</div></div>)}</div></section>}
function StaffModal({onClose,onSubmit}:{onClose:()=>void;onSubmit:(e:React.FormEvent<HTMLFormElement>)=>void}){return <div className="modal-backdrop"><form className="modal" onSubmit={onSubmit}><div className="modal-title"><h2>Thêm nhân viên</h2><button type="button" onClick={onClose}><X/></button></div><input name="full_name" required placeholder="Họ và tên *"/><input name="email" required type="email" placeholder="Email đăng nhập *"/><input name="password" required minLength={8} type="password" placeholder="Mật khẩu tạm thời (≥8 ký tự)"/><select name="role"><option value="sale">Sale</option><option value="admin">Admin</option></select><select name="branch"><option>Bắc Ninh</option><option>Lạng Sơn</option></select><div className="modal-actions"><button type="button" onClick={onClose}>Hủy</button><button className="primary"><UserPlus size={15}/> Tạo tài khoản</button></div></form></div>}
function ResetModal({staff,onClose,onSubmit}:{staff:Profile;onClose:()=>void;onSubmit:(e:React.FormEvent<HTMLFormElement>)=>void}){return <div className="modal-backdrop"><form className="modal" onSubmit={onSubmit}><div className="modal-title"><div><h2>Đặt lại mật khẩu</h2><p>{staff.full_name} • {staff.email}</p></div><button type="button" onClick={onClose}><X/></button></div><input name="password" required minLength={8} type="password" placeholder="Mật khẩu mới (≥8 ký tự)"/><input name="confirm" required minLength={8} type="password" placeholder="Nhập lại mật khẩu"/><div className="modal-actions"><button type="button" onClick={onClose}>Hủy</button><button className="primary"><KeyRound size={15}/> Cập nhật</button></div></form></div>}
function Login(){const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[forgot,setForgot]=useState(false),[resetEmail,setResetEmail]=useState('');async function submit(e:React.FormEvent){e.preventDefault();if(!supabase)return;setBusy(true);setError('');const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setError(error.message);setBusy(false);}async function reset(){if(!supabase)return;setBusy(true);setError('');const target=resetEmail||email;if(!target){setError('Nhập email tài khoản.');setBusy(false);return;}const {error}=await supabase.auth.resetPasswordForEmail(target,{redirectTo:location.origin+location.pathname});if(error)setError(error.message);else{setError('Đã gửi email khôi phục. Hãy kiểm tra hộp thư và thư rác.');setForgot(false);}setBusy(false);}return <div className="login"><div className="login-card"><div className="logo big">LH</div><h1>Liên Hoa CRM</h1><p>Quản trị Lead • Nhân sự • Chăm sóc khách hàng</p><form onSubmit={submit}><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email tài khoản" autoComplete="username"/><input required type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Mật khẩu" autoComplete="current-password"/><button className="primary full" disabled={busy}>{busy?<Loader2 size={15}/>:null} Đăng nhập</button></form>{error&&<div className="error">{error}</div>}<button className="recovery-link" onClick={()=>{setResetEmail(email);setForgot(true)}}><KeyRound size={15}/> Quên mật khẩu?</button>{forgot&&<div className="forgot-box"><input type="email" value={resetEmail} onChange={e=>setResetEmail(e.target.value)} placeholder="Email nhận link khôi phục"/><div><button type="button" onClick={()=>setForgot(false)}>Đóng</button><button type="button" className="primary" onClick={reset} disabled={busy}>Gửi email khôi phục</button></div></div>}</div></div>}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
