import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Users, UserRound, Bell, DollarSign, CheckCircle2, Clock3, LogOut, Plus, Search, Shield, UserCog, RefreshCw } from 'lucide-react';
import { supabase } from './lib/supabase';
import './styles.css';

type Role = 'director' | 'admin' | 'sale';
type Lead = { id:string; full_name:string; phone:string|null; course:string|null; source:string; branch:string|null; status:string; assigned_to:string|null; notes:string|null; next_follow_up:string|null; created_at:string; assignee?: {full_name:string}|null };
type Profile = { id:string; full_name:string; role:Role; branch:string|null; active:boolean };

const statusLabels: Record<string,string> = { new:'Mới', consulting:'Đang tư vấn', interested:'Đã quan tâm', follow_up:'Chờ follow-up', closed:'Đã chốt', lost:'Mất lead' };
const demoLeads: Lead[] = [
 {id:'demo-1',full_name:'Nguyễn Thị Lan',phone:'09•••123',course:'Tiếng Trung giao tiếp',source:'Facebook',branch:'Lạng Sơn',status:'new',assigned_to:null,notes:null,next_follow_up:null,created_at:new Date().toISOString()},
 {id:'demo-2',full_name:'Trần Văn Nam',phone:'09•••456',course:'HSK 1–2',source:'Facebook Ads',branch:'Bắc Ninh',status:'consulting',assigned_to:null,notes:null,next_follow_up:null,created_at:new Date().toISOString()},
];

function App(){
 const [session,setSession]=useState<any>(null); const [profile,setProfile]=useState<Profile|null>(null); const [leads,setLeads]=useState<Lead[]>([]); const [staff,setStaff]=useState<Profile[]>([]); const [query,setQuery]=useState(''); const [status,setStatus]=useState('all'); const [showAdd,setShowAdd]=useState(false); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 useEffect(()=>{ if(!supabase){setLoading(false);return;} supabase.auth.getSession().then(({data})=>setSession(data.session)); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return ()=>subscription.unsubscribe(); },[]);
 useEffect(()=>{ if(session?.user) loadData(); else if(!supabase) setLeads(demoLeads); },[session]);
 async function loadData(){ if(!supabase||!session) return; setLoading(true); setError(''); const [{data:p,error:pe},{data:l,error:le},{data:s,error:se}]=await Promise.all([
   supabase.from('profiles').select('id,full_name,role,branch,active').eq('id',session.user.id).single(),
   supabase.from('leads').select('*,assignee:profiles!leads_assigned_to_fkey(full_name)').order('created_at',{ascending:false}),
   supabase.from('profiles').select('id,full_name,role,branch,active').eq('active',true).order('full_name')
 ]); if(pe) setError(pe.message); if(le) setError(le.message); if(se) setError(se.message); setProfile(p); setLeads(l||[]); setStaff(s||[]); setLoading(false); }
 async function signOut(){await supabase?.auth.signOut();}
 const visible=useMemo(()=>leads.filter(l=>(status==='all'||l.status===status)&&[l.full_name,l.phone,l.course,l.source,l.branch].join(' ').toLowerCase().includes(query.toLowerCase())),[leads,query,status]);
 async function addLead(e:React.FormEvent<HTMLFormElement>){e.preventDefault(); if(!supabase||!session)return; const f=new FormData(e.currentTarget); const {error}=await supabase.from('leads').insert({full_name:f.get('full_name'),phone:f.get('phone'),course:f.get('course'),source:f.get('source')||'manual',branch:f.get('branch'),notes:f.get('notes'),created_by:session.user.id}); if(error)setError(error.message); else {setShowAdd(false);loadData();}}
 async function assign(id:string,value:string){if(!supabase)return; const {error}=await supabase.from('leads').update({assigned_to:value||null}).eq('id',id); if(error)setError(error.message); else loadData();}
 async function updateStatus(id:string,value:string){if(!supabase)return; const {error}=await supabase.from('leads').update({status:value}).eq('id',id); if(error)setError(error.message); else loadData();}
 if(!supabase) return <Login onDemo={()=>setSession({user:{id:'demo'}})} demo/>;
 if(!session) return <Login/>;
 const canManage=profile?.role==='director'||profile?.role==='admin';
 return <div className="app"><aside><div className="brand"><div className="logo">LH</div><div><b>LIÊN HOA</b><small>GLOBAL EDUCATION</small></div></div><nav><a className="active">Inbox / Leads</a><a>Khách hàng</a><a>Sale & Phân bổ</a><a>Follow-up</a><a>Khóa học</a><a>Thu học phí</a><a>KPI & Báo cáo</a>{canManage&&<a>Quản trị nhân sự</a>}</nav><div className="side-foot"><div className="user"><UserCog size={14}/><span>{profile?.full_name||session.user.email}</span></div><small>{profile?.role?.toUpperCase()||'SALE'} {profile?.branch?`• ${profile.branch}`:''}</small><button onClick={signOut}><LogOut size={14}/> Đăng xuất</button></div></aside>
 <main><header><div><h1>Inbox / Leads</h1><p>Lead Facebook, Inbox và Lead nhập tay</p></div><div className="header-actions"><button className="icon-btn" onClick={loadData}><RefreshCw size={17}/></button><button className="notify"><Bell size={18}/><span>3</span></button></div></header>
 {error&&<div className="error">{error}</div>}
 <section className="cards"><Card icon={<Users/>} label="Tổng Lead" value={String(leads.length)} note="Theo quyền truy cập"/><Card icon={<UserRound/>} label="Đang chăm sóc" value={String(leads.filter(x=>['consulting','interested','follow_up'].includes(x.status)).length)} note="Cần follow-up"/><Card icon={<CheckCircle2/>} label="Đã chốt" value={String(leads.filter(x=>x.status==='closed').length)} note="Lead đã chốt"/><Card icon={<DollarSign/>} label="Quyền" value={profile?.role?.toUpperCase()||'SALE'} note={profile?.branch||'Toàn hệ thống'}/></section>
 <section className="panel"><div className="panel-head"><div><h2>Danh sách Lead</h2><p>{visible.length} Lead đang hiển thị</p></div><button className="primary" onClick={()=>setShowAdd(true)}><Plus size={15}/> Thêm Lead</button></div><div className="filters"><div className="search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm tên, SĐT, khóa học..."/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Tất cả trạng thái</option>{Object.entries(statusLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div><div className="table-wrap"><table><thead><tr><th>Khách hàng</th><th>Nhu cầu</th><th>Nguồn / Cơ sở</th><th>Sale phụ trách</th><th>Trạng thái</th><th>Follow-up</th></tr></thead><tbody>{visible.map(l=><tr key={l.id}><td><b>{l.full_name}</b><small>{l.phone||'Chưa có SĐT'}</small></td><td>{l.course||'—'}</td><td>{l.source}<small>{l.branch||'—'}</small></td><td>{canManage?<select className="inline" value={l.assigned_to||''} onChange={e=>assign(l.id,e.target.value)}><option value="">Chưa phân</option>{staff.filter(x=>x.role==='sale').map(s=><option key={s.id} value={s.id}>{s.full_name}</option>)}</select>:<span>{l.assignee?.full_name||'Chưa phân'}</span>}</td><td><select className="inline" value={l.status} onChange={e=>updateStatus(l.id,e.target.value)}>{Object.entries(statusLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></td><td>{l.next_follow_up?new Date(l.next_follow_up).toLocaleString('vi-VN'):'Chưa đặt'}</td></tr>)}</tbody></table></div></section>
 </main>{showAdd&&<div className="modal-backdrop"><form className="modal" onSubmit={addLead}><h2>Thêm Lead mới</h2><input name="full_name" required placeholder="Họ và tên"/><input name="phone" placeholder="Số điện thoại"/><input name="course" placeholder="Khóa học / nhu cầu"/><select name="source"><option>Facebook</option><option>Facebook Ads</option><option>Inbox</option><option>Website</option><option>Giới thiệu</option><option>manual</option></select><select name="branch"><option>Bắc Ninh</option><option>Lạng Sơn</option></select><textarea name="notes" placeholder="Ghi chú"></textarea><div className="modal-actions"><button type="button" onClick={()=>setShowAdd(false)}>Hủy</button><button className="primary">Lưu Lead</button></div></form></div>}</div>
}
function Login({onDemo,demo=false}:{onDemo?:()=>void;demo?:boolean}){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [msg,setMsg]=useState('');async function login(e:React.FormEvent){e.preventDefault();if(!supabase)return;const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setMsg(error.message)} return <div className="login"><div className="login-card"><div className="logo big">LH</div><h1>Liên Hoa CRM</h1><p>Đăng nhập hệ thống Sales & CSKH</p>{demo?<><div className="demo-note">Chưa cấu hình Supabase. Đây là chế độ demo.</div><button className="primary full" onClick={onDemo}>Vào bản demo</button></>:<form onSubmit={login}><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email nhân viên"/><input type="password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Mật khẩu"/>{msg&&<div className="error">{msg}</div>}<button className="primary full">Đăng nhập</button></form>}</div></div>}
function Card({icon,label,value,note}:{icon:React.ReactNode,label:string,value:string,note:string}){return <div className="card"><div className="card-icon">{icon}</div><div className="label">{label}</div><div className="value">{value}</div><div className="note">{note}</div></div>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
