import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { supabase } from './lib/supabase';
import './styles.css';
import './crm.css';
import './messenger.css';
import { Bell, Check, LogOut, MessageCircle, RefreshCw, Send, UserRound, Phone, CalendarClock, StickyNote, X } from 'lucide-react';

type Role='director'|'admin'|'sale';
type Profile={id:string;full_name:string;email:string|null;role:Role;branch:string|null;active:boolean};
type Lead={id:string;full_name:string;phone:string|null;email:string|null;course:string|null;source:string;branch:string|null;status:string;assigned_to:string|null;notes:string|null;next_follow_up:string|null;assignee?:{full_name:string}|null};
type Conversation={id:string;page_id:string;sender_id:string;thread_id:string;lead_id:string|null;last_message:string|null;last_message_at:string|null;unread_count:number;lead?:Lead|null};
type FbMessage={id:string;conversation_id:string;message_id:string|null;sender_id:string;recipient_id:string;direction:'inbound'|'outbound';message_text:string|null;message_at:string;status:string;error_message:string|null};
const statuses:Record<string,string>={new:'Mới',consulting:'Đang tư vấn',interested:'Đã quan tâm',follow_up:'Chờ follow-up',closed:'Đã chốt',lost:'Mất lead'};
const fmt=(d:string|null)=>d?new Date(d).toLocaleString('vi-VN',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'';

function App(){
 const [session,setSession]=useState<any>(null),[profile,setProfile]=useState<Profile|null>(null),[staff,setStaff]=useState<Profile[]>([]),[conversations,setConversations]=useState<Conversation[]>([]),[selected,setSelected]=useState<Conversation|null>(null),[messages,setMessages]=useState<FbMessage[]>([]);
 const [text,setText]=useState(''),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[sending,setSending]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[followDate,setFollowDate]=useState(''),[note,setNote]=useState('');
 useEffect(()=>{if(!supabase){setLoading(false);return;} supabase.auth.getSession().then(({data})=>setSession(data.session));const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe();},[]);
 useEffect(()=>{if(session?.user)load();},[session]);
 async function load(){if(!supabase||!session)return;setLoading(true);setError('');const [{data:p,error:pe},{data:c,error:ce},{data:s,error:se}]=await Promise.all([
  supabase.from('profiles').select('id,full_name,email,role,branch,active').eq('id',session.user.id).single(),
  supabase.from('facebook_conversations').select('id,page_id,sender_id,thread_id,lead_id,last_message,last_message_at,unread_count,lead:leads(id,full_name,phone,email,course,source,branch,status,assigned_to,notes,next_follow_up,assignee:profiles!leads_assigned_to_fkey(full_name))').order('last_message_at',{ascending:false}),
  supabase.from('profiles').select('id,full_name,email,role,branch,active').eq('active',true).order('full_name')
 ]);if(pe){setError(pe.message);return;}if(ce)setError(ce.message);if(se)setError(se.message);setProfile(p);setConversations((c||[]) as any);setStaff(s||[]);setLoading(false);}
 const visible=useMemo(()=>conversations.filter(c=>{const l=c.lead;return [l?.full_name,l?.phone,l?.course,c.last_message,c.sender_id].join(' ').toLowerCase().includes(search.toLowerCase());}),[conversations,search]);
 async function openConversation(c:Conversation){setSelected(c);setError('');if(!supabase)return;const {data,error}=await supabase.from('facebook_messages').select('*').eq('conversation_id',c.id).order('message_at',{ascending:true});if(error)setError(error.message);setMessages((data||[]) as FbMessage[]);await supabase.from('facebook_conversations').update({unread_count:0}).eq('id',c.id);setConversations(prev=>prev.map(x=>x.id===c.id?{...x,unread_count:0}:x));}
 async function sendMessage(){if(!supabase||!selected||!text.trim()||sending)return;setSending(true);setError('');const value=text.trim();const {data,error}=await supabase.functions.invoke('facebook-send-message',{body:{conversation_id:selected.id,message:value}});if(error||data?.error){setError(error?.message||data?.error||'Không gửi được tin nhắn.');setSending(false);return;}setText('');setNotice('Đã gửi tin nhắn.');await openConversation(selected);await load();setSending(false);}
 async function updateLead(patch:Partial<Lead>){if(!supabase||!selected?.lead_id)return;const {error}=await supabase.from('leads').update(patch).eq('id',selected.lead_id);if(error)setError(error.message);else{setNotice('Đã cập nhật Lead.');await load();const fresh=conversations.find(x=>x.id===selected.id);if(fresh)await openConversation(fresh);}}
 async function addNote(){if(!supabase||!selected?.lead_id||!note.trim())return;const {error}=await supabase.from('lead_activities').insert({lead_id:selected.lead_id,actor_id:session.user.id,activity_type:'note',content:note.trim()});if(error)setError(error.message);else{setNote('');setNotice('Đã lưu ghi chú.');}}
 async function addFollow(){if(!supabase||!selected?.lead_id||!followDate)return;const iso=new Date(followDate).toISOString();const {error}=await supabase.from('follow_ups').insert({lead_id:selected.lead_id,assigned_to:selected.lead?.assigned_to||session.user.id,due_at:iso,status:'pending',note:'Follow-up từ Inbox Facebook'});if(error)setError(error.message);else{await supabase.from('leads').update({next_follow_up:iso,status:'follow_up'}).eq('id',selected.lead_id);setFollowDate('');setNotice('Đã đặt follow-up.');await load();}}
 async function signOut(){await supabase?.auth.signOut();}
 if(!supabase)return <div className="login"><div className="login-card"><h1>Liên Hoa CRM</h1><p>Chưa cấu hình Supabase.</p></div></div>;
 if(!session)return <div className="login"><div className="login-card"><div className="logo big">LH</div><h1>Liên Hoa CRM</h1><p>Vui lòng đăng nhập từ CRM.</p><a href={location.pathname}>Quay lại</a></div></div>;
 return <div className="app"><aside><div className="brand"><div className="logo">LH</div><div><b>LIÊN HOA</b><small>GLOBAL EDUCATION</small></div></div><nav><a className="active"><MessageCircle size={15}/>Inbox Facebook</a><a onClick={()=>location.href=location.pathname}>CRM / Leads</a></nav><div className="side-foot"><div className="user"><UserRound size={14}/><span>{profile?.full_name||session.user.email}</span></div><small>{profile?.role?.toUpperCase()||'SALE'} • {profile?.branch||'TOÀN HỆ THỐNG'}</small><button onClick={signOut}><LogOut size={14}/> Đăng xuất</button></div></aside>
 <main className="messenger-main"><header><div><h1>Inbox Facebook</h1><p>Messenger → Lead → Sale → Follow-up</p></div><div className="header-actions"><button className="icon-btn" onClick={load} disabled={loading}><RefreshCw size={17}/></button><button className="notify"><Bell size={18}/></button></div></header>{error&&<div className="error">{error}<button onClick={()=>setError('')}><X size={13}/></button></div>}{notice&&<div className="success">{notice}<button onClick={()=>setNotice('')}><X size={13}/></button></div>}
 <div className="messenger-shell"><section className="conversation-list"><div className="inbox-head"><div><b>Hội thoại</b><span>{visible.length}</span></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Tìm khách..."/></div>{loading?<div className="empty">Đang tải...</div>:visible.length===0?<div className="empty"><MessageCircle size={30}/><b>Chưa có hội thoại Messenger</b><small>Hãy nhắn thử từ một tài khoản Facebook khác vào Fanpage.</small></div>:visible.map(c=><button key={c.id} className={'conversation-item '+(selected?.id===c.id?'selected':'')} onClick={()=>openConversation(c)}><div className="avatar">{(c.lead?.full_name||'FB').slice(0,1).toUpperCase()}</div><div className="conv-copy"><div><b>{c.lead?.full_name||`Facebook ${c.sender_id.slice(-6)}`}</b>{c.unread_count>0&&<em>{c.unread_count}</em>}</div><p>{c.last_message||'Tin nhắn mới'}</p><small>{fmt(c.last_message_at)}</small></div></button>)}</section>
 <section className="chat-panel">{!selected?<div className="empty chat-empty"><MessageCircle size={48}/><h2>Chọn một cuộc hội thoại</h2><p>Tất cả tin nhắn Facebook sẽ được xử lý tại đây.</p></div>:<><div className="chat-head"><div className="avatar">{(selected.lead?.full_name||'FB').slice(0,1).toUpperCase()}</div><div><h2>{selected.lead?.full_name||`Facebook ${selected.sender_id.slice(-6)}`}</h2><small>{selected.lead?.phone||'Messenger'} • {selected.lead?.course||'Chưa xác định nhu cầu'}</small></div><div className="chat-actions">{selected.lead?.phone&&<button onClick={()=>location.href=`tel:${selected.lead?.phone}`} title="Gọi"><Phone size={17}/></button>}<button onClick={()=>openConversation(selected)} title="Tải lại"><RefreshCw size={17}/></button></div></div>
 <div className="messages">{messages.length===0?<div className="empty">Chưa có tin nhắn được lưu.</div>:messages.map(m=><div key={m.id} className={'bubble-row '+(m.direction==='outbound'?'outbound':'inbound')}><div className="bubble">{m.message_text||'[Tin nhắn không phải văn bản]'}<small>{fmt(m.message_at)} {m.direction==='outbound'&&<>{m.status==='sent'?<Check size={12}/>:m.status}</>}</small></div></div>)}</div>
 <div className="composer"><textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage();}}} placeholder="Nhập tin nhắn trả lời..."/><button onClick={sendMessage} disabled={sending||!text.trim()}><Send size={17}/>{sending?'Đang gửi':'Gửi'}</button></div></>}</section>
 <aside className="lead-panel">{selected?.lead?<><div className="lead-panel-head"><b>Thông tin Lead</b><span className="source-pill">FACEBOOK</span></div><div className="lead-person"><div className="avatar large">{selected.lead.full_name.slice(0,1).toUpperCase()}</div><div><h3>{selected.lead.full_name}</h3><p>{selected.lead.phone||'Chưa có SĐT'}</p></div></div><label>Sale phụ trách<select value={selected.lead.assigned_to||''} onChange={e=>updateLead({assigned_to:e.target.value||null})}><option value="">Chưa phân</option>{staff.filter(s=>s.role==='sale'&&s.active).map(s=><option key={s.id} value={s.id}>{s.full_name}{s.branch?` • ${s.branch}`:''}</option>)}</select></label><label>Trạng thái<select value={selected.lead.status} onChange={e=>updateLead({status:e.target.value})}>{Object.entries(statuses).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Khóa học<input value={selected.lead.course||''} onChange={e=>updateLead({course:e.target.value})} placeholder="HSK1 / Giao tiếp..."/></label><div className="quick-block"><b><CalendarClock size={15}/> Follow-up</b><input type="datetime-local" value={followDate} onChange={e=>setFollowDate(e.target.value)}/><button onClick={addFollow}>Đặt lịch</button></div><div className="quick-block"><b><StickyNote size={15}/> Ghi chú</b><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Ghi chú khách hàng..."/><button onClick={addNote}>Lưu ghi chú</button></div><div className="lead-meta"><span>Nguồn: {selected.lead.source}</span><span>Cơ sở: {selected.lead.branch||'Chưa chọn'}</span><span>Trạng thái: {statuses[selected.lead.status]||selected.lead.status}</span></div></>:<div className="empty">Chọn hội thoại để xem Lead.</div>}</aside></div></main></div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
