import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowLeft, Banknote, Building2, CalendarDays, CheckCircle2, GraduationCap, Plus, RefreshCw, Search, WalletCards, X } from 'lucide-react';
import { supabase } from './lib/supabase';
import './styles.css';

type ClassRow={id:string;name:string;course:string|null;branch:string;teacher_name:string|null;start_date:string|null;end_date:string|null;total_sessions:number|null;list_tuition:number;status:string};
type Student={id:string;full_name:string;phone:string|null;email:string|null;branch:string|null;lead_id:string|null;created_at:string};
type Enrollment={id:string;student_id:string;class_id:string;list_price:number;discount_amount:number;final_price:number;status:string;enrolled_at:string;student?:Student;class?:ClassRow};
type Payment={id:string;enrollment_id:string;amount:number;paid_at:string;method:string;reference:string|null;note:string|null;received_by:string|null};
const money=(n:number)=>new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND',maximumFractionDigits:0}).format(Number(n)||0);
const methodLabel:Record<string,string>={cash:'Tiền mặt',bank_transfer:'Chuyển khoản',qr:'QR',card:'Thẻ',other:'Khác'};
const statusLabel:Record<string,string>={planned:'Dự kiến',active:'Đang học',completed:'Đã kết thúc',cancelled:'Đã hủy'};

function App(){
 const [session,setSession]=useState<any>(null); const [profile,setProfile]=useState<any>(null); const [classes,setClasses]=useState<ClassRow[]>([]); const [students,setStudents]=useState<Student[]>([]); const [enrollments,setEnrollments]=useState<Enrollment[]>([]); const [payments,setPayments]=useState<Payment[]>([]); const [page,setPage]=useState<'overview'|'classes'|'students'|'payments'>('overview'); const [branch,setBranch]=useState('all'); const [query,setQuery]=useState(''); const [showClass,setShowClass]=useState(false); const [showStudent,setShowStudent]=useState(false); const [showPayment,setShowPayment]=useState(false); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 useEffect(()=>{if(!supabase){setLoading(false);return} supabase.auth.getSession().then(({data})=>setSession(data.session)); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(session?.user)load()},[session]);
 async function load(){if(!supabase||!session)return;setLoading(true);setError(''); const [p,c,s,e,pay]=await Promise.all([
   supabase.from('profiles').select('id,full_name,email,role,branch,active').eq('id',session.user.id).single(),
   supabase.from('classes').select('*').order('start_date',{ascending:false}),
   supabase.from('students').select('*').order('created_at',{ascending:false}),
   supabase.from('enrollments').select('*,student:students(*),class:classes(*)').order('enrolled_at',{ascending:false}),
   supabase.from('payments').select('*').order('paid_at',{ascending:false})
 ]); if(p.error){setError(p.error.message);await supabase.auth.signOut();return} if(!p.data?.active){setError('Tài khoản đã bị vô hiệu hóa.');await supabase.auth.signOut();return} if(c.error||s.error||e.error||pay.error)setError((c.error||s.error||e.error||pay.error)?.message||'Không tải được dữ liệu'); setProfile(p.data);setClasses(c.data||[]);setStudents(s.data||[]);setEnrollments(e.data||[]);setPayments(pay.data||[]);setLoading(false)}
 if(!supabase||!session)return <div className="login"><div className="login-card"><div className="logo big">LH</div><h1>Thu học phí</h1><p>Hãy đăng nhập Liên Hoa CRM trước.</p><button className="primary full" onClick={()=>window.location.href=window.location.pathname}>Quay lại CRM</button></div></div>;
 if(profile?.role==='sale')return <div className="login"><div className="login-card"><div className="logo big">LH</div><h1>Thu học phí</h1><p>Tài khoản Sale chỉ được xem dữ liệu học viên được phân.</p><button className="primary full" onClick={()=>window.location.href=window.location.pathname}>Quay lại CRM</button></div></div>;
 const revenue=payments.reduce((a,p)=>a+Number(p.amount),0); const contracted=enrollments.reduce((a,e)=>a+Number(e.final_price),0); const debt=Math.max(0,contracted-revenue); const filteredStudents=students.filter(s=>(branch==='all'||s.branch===branch)&&[s.full_name,s.phone,s.email,s.branch].join(' ').toLowerCase().includes(query.toLowerCase()));
 const branchRevenue=(b:string)=>payments.reduce((sum,p)=>{const e=enrollments.find(x=>x.id===p.enrollment_id);const c=e&&classes.find(x=>x.id===e.class_id);return sum+(c?.branch===b?Number(p.amount):0)},0);
 return <div className="app"><aside><div className="brand"><div className="logo">LH</div><div><b>LIÊN HOA</b><small>GLOBAL EDUCATION</small></div></div><nav><a onClick={()=>window.location.href=window.location.pathname}><ArrowLeft size={14}/> CRM chính</a><a className={page==='overview'?'active':''} onClick={()=>setPage('overview')}><WalletCards size={14}/> Tổng quan doanh thu</a><a className={page==='classes'?'active':''} onClick={()=>setPage('classes')}><GraduationCap size={14}/> Lớp học</a><a className={page==='students'?'active':''} onClick={()=>setPage('students')}><Building2 size={14}/> Học viên</a><a className={page==='payments'?'active':''} onClick={()=>setPage('payments')}><Banknote size={14}/> Phiếu thu</a></nav><div className="side-foot"><div className="user"><Building2 size={14}/><span>{profile?.full_name}</span></div><small>{String(profile?.role||'').toUpperCase()} • THU HỌC PHÍ</small></div></aside>
 <main><header><div><h1>Thu học phí & Doanh thu</h1><p>Quản lý học viên, lớp, giảm giá, công nợ và lịch sử thu tiền</p></div><div className="header-actions"><button className="icon-btn" onClick={load} disabled={loading}><RefreshCw size={17}/></button></div></header>{error&&<div className="error">{error}<button onClick={()=>setError('')}><X size={13}/></button></div>}
 {page==='overview'&&<><section className="cards"><Card label="Doanh thu đã thu" value={money(revenue)} note="Tổng phiếu thu" icon={<Banknote/>}/><Card label="Doanh thu hợp đồng" value={money(contracted)} note="Sau giảm giá" icon={<CheckCircle2/>}/><Card label="Công nợ" value={money(debt)} note="Chưa thu" icon={<WalletCards/>}/><Card label="Học viên" value={String(students.length)} note={`${enrollments.length} lượt đăng ký`} icon={<GraduationCap/>}/></section><section className="cards"><Card label="Bắc Ninh" value={money(branchRevenue('Bắc Ninh'))} note="Doanh thu đã thu" icon={<Building2/>}/><Card label="Lạng Sơn" value={money(branchRevenue('Lạng Sơn'))} note="Doanh thu đã thu" icon={<Building2/>}/></section><section className="panel"><div className="panel-head"><div><h2>Đăng ký gần đây</h2><p>Theo dõi giá gốc → giảm giá → phải thu → đã thu → còn nợ</p></div><button className="primary" onClick={()=>setShowPayment(true)}><Plus size={15}/> Thu học phí</button></div><div className="table-wrap"><table><thead><tr><th>Học viên</th><th>Lớp</th><th>Cơ sở</th><th>Giá niêm yết</th><th>Giảm</th><th>Phải thu</th><th>Đã thu</th><th>Còn nợ</th></tr></thead><tbody>{enrollments.slice(0,12).map(e=>{const paid=payments.filter(p=>p.enrollment_id===e.id).reduce((a,p)=>a+Number(p.amount),0);return <tr key={e.id}><td><b>{e.student?.full_name}</b><small>{e.student?.phone||'—'}</small></td><td>{e.class?.name||'—'}</td><td>{e.class?.branch||e.student?.branch||'—'}</td><td>{money(e.list_price)}</td><td>{money(e.discount_amount)}</td><td>{money(e.final_price)}</td><td>{money(paid)}</td><td>{money(Math.max(0,Number(e.final_price)-paid))}</td></tr>})}</tbody></table></div></section></>}
 {page==='classes'&&<section className="panel"><div className="panel-head"><div><h2>Danh sách lớp</h2><p>{classes.length} lớp</p></div><button className="primary" onClick={()=>setShowClass(true)}><Plus size={15}/> Thêm lớp</button></div><div className="filters"><select value={branch} onChange={e=>setBranch(e.target.value)}><option value="all">Tất cả cơ sở</option><option>Bắc Ninh</option><option>Lạng Sơn</option></select></div><div className="table-wrap"><table><thead><tr><th>Lớp</th><th>Khóa học</th><th>Cơ sở</th><th>Giảng viên</th><th>Thời gian</th><th>Học phí</th><th>Trạng thái</th></tr></thead><tbody>{classes.filter(c=>branch==='all'||c.branch===branch).map(c=><tr key={c.id}><td><b>{c.name}</b></td><td>{c.course||'—'}</td><td>{c.branch}</td><td>{c.teacher_name||'—'}</td><td>{c.start_date||'—'} → {c.end_date||'—'}</td><td>{money(c.list_tuition)}</td><td><span className="role-pill">{statusLabel[c.status]||c.status}</span></td></tr>)}</tbody></table></div></section>}
 {page==='students'&&<section className="panel"><div className="panel-head"><div><h2>Học viên</h2><p>{filteredStudents.length} học viên</p></div><button className="primary" onClick={()=>setShowStudent(true)}><Plus size={15}/> Thêm học viên</button></div><div className="filters"><div className="search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm tên, SĐT, email..."/></div><select value={branch} onChange={e=>setBranch(e.target.value)}><option value="all">Tất cả cơ sở</option><option>Bắc Ninh</option><option>Lạng Sơn</option></select></div><div className="table-wrap"><table><thead><tr><th>Học viên</th><th>SĐT</th><th>Email</th><th>Cơ sở</th><th>Đăng ký</th><th>Tổng phải thu</th><th>Đã thu</th><th>Còn nợ</th></tr></thead><tbody>{filteredStudents.map(s=>{const es=enrollments.filter(e=>e.student_id===s.id);const due=es.reduce((a,e)=>a+Number(e.final_price),0);const paid=es.reduce((a,e)=>a+payments.filter(p=>p.enrollment_id===e.id).reduce((x,p)=>x+Number(p.amount),0),0);return <tr key={s.id}><td><b>{s.full_name}</b></td><td>{s.phone||'—'}</td><td>{s.email||'—'}</td><td>{s.branch||'—'}</td><td>{es.length}</td><td>{money(due)}</td><td>{money(paid)}</td><td>{money(Math.max(0,due-paid))}</td></tr>})}</tbody></table></div></section>}
 {page==='payments'&&<section className="panel"><div className="panel-head"><div><h2>Phiếu thu học phí</h2><p>{payments.length} giao dịch</p></div><button className="primary" onClick={()=>setShowPayment(true)}><Plus size={15}/> Ghi nhận thu tiền</button></div><div className="table-wrap"><table><thead><tr><th>Ngày thu</th><th>Học viên</th><th>Lớp</th><th>Số tiền</th><th>Phương thức</th><th>Mã giao dịch</th><th>Ghi chú</th></tr></thead><tbody>{payments.map(p=>{const e=enrollments.find(x=>x.id===p.enrollment_id);return <tr key={p.id}><td>{new Date(p.paid_at).toLocaleString('vi-VN')}</td><td>{e?.student?.full_name||'—'}</td><td>{e?.class?.name||'—'}</td><td><b>{money(p.amount)}</b></td><td>{methodLabel[p.method]||p.method}</td><td>{p.reference||'—'}</td><td>{p.note||'—'}</td></tr>})}</tbody></table></div></section>}
 </main>
 {showClass&&<ClassModal onClose={()=>setShowClass(false)} onSaved={load}/>} {showStudent&&<StudentModal onClose={()=>setShowStudent(false)} onSaved={load}/>} {showPayment&&<PaymentModal enrollments={enrollments} onClose={()=>setShowPayment(false)} onSaved={load}/>} </div>
}
function Card({label,value,note,icon}:{label:string;value:string;note:string;icon:React.ReactNode}){return <div className="card"><div className="card-icon">{icon}</div><div className="label">{label}</div><div className="value">{value}</div><div className="note">{note}</div></div>}
function ClassModal({onClose,onSaved}:{onClose:()=>void;onSaved:()=>void}){async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;const f=new FormData(e.currentTarget);const {error}=await supabase.from('classes').insert({name:f.get('name'),course:f.get('course')||null,branch:f.get('branch'),teacher_name:f.get('teacher_name')||null,start_date:f.get('start_date')||null,end_date:f.get('end_date')||null,total_sessions:Number(f.get('total_sessions')||0)||null,list_tuition:Number(f.get('list_tuition')||0),status:f.get('status')});if(error)alert(error.message);else{onClose();onSaved()}}return <Modal title="Thêm lớp học" onClose={onClose}><form onSubmit={submit}><input name="name" required placeholder="Tên lớp, ví dụ: Giao tiếp Trung cơ bản K10"/><input name="course" placeholder="Khóa học"/><select name="branch"><option>Bắc Ninh</option><option>Lạng Sơn</option></select><input name="teacher_name" placeholder="Tên giảng viên"/><div className="form-grid"><label>Ngày bắt đầu<input name="start_date" type="date"/></label><label>Ngày kết thúc<input name="end_date" type="date"/></label></div><div className="form-grid"><input name="total_sessions" type="number" placeholder="Số buổi"/><input name="list_tuition" type="number" placeholder="Học phí niêm yết"/></div><select name="status"><option value="planned">Dự kiến</option><option value="active">Đang học</option><option value="completed">Đã kết thúc</option><option value="cancelled">Đã hủy</option></select><div className="modal-actions"><button type="button" onClick={onClose}>Hủy</button><button className="primary">Lưu lớp</button></div></form></Modal>}
function StudentModal({onClose,onSaved}:{onClose:()=>void;onSaved:()=>void}){async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;const f=new FormData(e.currentTarget);const {error}=await supabase.from('students').insert({full_name:f.get('full_name'),phone:f.get('phone')||null,email:f.get('email')||null,branch:f.get('branch')});if(error)alert(error.message);else{onClose();onSaved()}}return <Modal title="Thêm học viên" onClose={onClose}><form onSubmit={submit}><input name="full_name" required placeholder="Họ và tên"/><input name="phone" placeholder="Số điện thoại"/><input name="email" type="email" placeholder="Email"/><select name="branch"><option>Bắc Ninh</option><option>Lạng Sơn</option></select><div className="modal-actions"><button type="button" onClick={onClose}>Hủy</button><button className="primary">Lưu học viên</button></div></form></Modal>}
function PaymentModal({enrollments,onClose,onSaved}:{enrollments:Enrollment[];onClose:()=>void;onSaved:()=>void}){async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;const f=new FormData(e.currentTarget);const enrollment_id=String(f.get('enrollment_id'));const amount=Number(f.get('amount')||0);if(!enrollment_id||amount<=0){alert('Chọn học viên và nhập số tiền hợp lệ.');return}const {error}=await supabase.from('payments').insert({enrollment_id,amount,paid_at:new Date(String(f.get('paid_at'))).toISOString(),method:f.get('method'),reference:f.get('reference')||null,note:f.get('note')||null,received_by:(await supabase.auth.getUser()).data.user?.id||null});if(error)alert(error.message);else{onClose();onSaved()}}return <Modal title="Ghi nhận thu học phí" onClose={onClose}><form onSubmit={submit}><select name="enrollment_id" required><option value="">Chọn học viên / lớp</option>{enrollments.map(e=><option key={e.id} value={e.id}>{e.student?.full_name} • {e.class?.name} • Còn {money(Math.max(0,Number(e.final_price)-0))}</option>)}</select><input name="amount" type="number" required placeholder="Số tiền thu"/><input name="paid_at" type="datetime-local" defaultValue={new Date().toISOString().slice(0,16)}/><select name="method"><option value="bank_transfer">Chuyển khoản</option><option value="qr">QR</option><option value="cash">Tiền mặt</option><option value="card">Thẻ</option><option value="other">Khác</option></select><input name="reference" placeholder="Mã giao dịch / nội dung chuyển khoản"/><textarea name="note" placeholder="Ghi chú"></textarea><div className="modal-actions"><button type="button" onClick={onClose}>Hủy</button><button className="primary">Lưu phiếu thu</button></div></form></Modal>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="modal-backdrop"><div className="modal"><div className="modal-title"><div><h2>{title}</h2></div><button className="close-btn" onClick={onClose}><X size={15}/></button></div>{children}</div></div>}
createRoot(document.getElementById('root')!).render(<App/>);
