import React, { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Banknote, Building2, CheckCircle2, GraduationCap, Pencil, Plus, RefreshCw, Search, Trash2, WalletCards, X } from 'lucide-react';
import { createRoot } from 'react-dom/client';
import { supabase } from './lib/supabase';
import './styles.css';

type ClassRow={id:string;name:string;course:string|null;branch:string;teacher_name:string|null;start_date:string|null;end_date:string|null;total_sessions:number|null;list_tuition:number;status:string};
type Student={id:string;full_name:string;phone:string|null;email:string|null;branch:string|null;lead_id:string|null;created_at:string;date_of_birth:string|null;gender:string|null;address:string|null};
type Enrollment={id:string;student_id:string;class_id:string;list_price:number;discount_amount:number;final_price:number;status:string;enrolled_at:string;student?:Student;class?:ClassRow};
type Payment={id:string;enrollment_id:string;amount:number;paid_at:string;method:string;reference:string|null;note:string|null;received_by:string|null};
const money=(n:number)=>new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND',maximumFractionDigits:0}).format(Number(n)||0);
const methodLabel:Record<string,string>={cash:'Tiền mặt',bank_transfer:'Chuyển khoản',qr:'QR',card:'Thẻ',other:'Khác'};
const receiptHtml=(p:Payment,enr:Enrollment,allPayments:Payment[])=>{
 const student=enr.student?.full_name||'—',phone=enr.student?.phone||'—',cls=enr.class?.name||'—',course=enr.class?.course||'—',branch=enr.class?.branch||enr.student?.branch||'—',no=p.id.slice(0,8).toUpperCase();
 const totalPaid=allPayments.filter(x=>x.enrollment_id===enr.id).reduce((a,x)=>a+Number(x.amount),0),remain=Math.max(0,Number(enr.final_price)-totalPaid);
 const safe=(v:any)=>String(v??'—').replace(/[&<>"]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[x]||x));
 const row=(l:string,v:any)=>'<div class="row"><b>'+l+'</b><span>'+safe(v)+'</span></div>';
 return '<!doctype html><html lang="vi"><head><meta charset="utf-8"><title>Bộ hồ sơ '+safe(no)+'</title><style>body{font-family:Arial,sans-serif;margin:0;color:#111}.page{max-width:780px;margin:auto;padding:30px 36px;box-sizing:border-box;min-height:100vh;page-break-after:always}.page:last-child{page-break-after:auto}h1{text-align:center;font-size:19px;margin:0}.sub{text-align:center;margin:5px 0 18px}.title{text-align:center;font-size:21px;margin:18px 0}.row{display:grid;grid-template-columns:190px 1fr;border-bottom:1px dotted #aaa;padding:8px 0}.section{font-weight:bold;border-bottom:1px solid #222;padding:8px 0;margin-top:18px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:8px 22px}.line{padding:7px 0;border-bottom:1px dotted #bbb}.sign{display:grid;grid-template-columns:1fr 1fr;text-align:center;margin-top:50px}.amount{font-size:21px;font-weight:bold}@media print{.page{min-height:auto;padding:16mm}}</style></head><body>'+
 '<div class="page"><h1>TRUNG TÂM NGOẠI NGỮ LIÊN HOA GLOBAL EDUCATION</h1><div class="sub">KẾT NỐI TRI THỨC – MỞ LỐI TƯƠNG LAI</div><div class="title">PHIẾU THU HỌC PHÍ</div>'+
 row('Số phiếu',no)+row('Ngày thu',new Date(p.paid_at).toLocaleString('vi-VN'))+row('Học viên',student)+row('Số điện thoại',phone)+row('Lớp',cls)+row('Khóa học',course)+row('Cơ sở',branch)+row('Phương thức',methodLabel[p.method]||p.method)+row('Mã giao dịch',p.reference||'—')+row('Số tiền đã thu',money(p.amount))+row('Tổng đã thu',money(totalPaid))+row('Còn phải hoàn thành',money(remain))+row('Ghi chú',p.note||'—')+
 '<div class="sign"><div><b>Người nộp tiền</b><br><br><br>'+safe(student)+'</div><div><b>Người thu tiền</b><br><br><br>Liên Hoa Global Education</div></div></div>'+
 '<div class="page"><h1>TRUNG TÂM NGOẠI NGỮ LIÊN HOA GLOBAL EDUCATION</h1><div class="sub">KẾT NỐI TRI THỨC – MỞ LỐI TƯƠNG LAI</div><div class="title">ĐƠN ĐĂNG KÝ NHẬP HỌC</div>'+
 '<div class="section">I. THÔNG TIN HỌC VIÊN</div><div class="grid"><div class="line"><b>Họ và tên*:</b> '+safe(student)+'</div><div class="line"><b>Ngày sinh*:</b> ................................</div><div class="line"><b>Giới tính:</b> ................................</div><div class="line"><b>Số điện thoại*:</b> '+safe(phone)+'</div><div class="line"><b>Email:</b> '+safe(enr.student?.email||'—')+'</div><div class="line"><b>Địa chỉ:</b> ................................</div></div>'+
 '<div class="section">II. THÔNG TIN KHÓA HỌC</div><div class="grid"><div class="line"><b>Khóa học đăng ký:</b> '+safe(course)+'</div><div class="line"><b>Lớp:</b> '+safe(cls)+'</div><div class="line"><b>Lịch / ca học đăng ký:</b> ................................</div><div class="line"><b>Ngày dự kiến bắt đầu:</b> '+safe(enr.class?.start_date||'—')+'</div><div class="line"><b>Học viên vào học từ buổi thứ:</b> ................................</div><div class="line"><b>Cơ sở:</b> '+safe(branch)+'</div></div>'+
 '<div class="section">THÔNG TIN HỌC PHÍ – ĐĂNG KÝ KHÓA HỌC</div><div class="grid"><div class="line">Nguyên giá: '+money(enr.list_price)+'</div><div class="line">Chương trình khuyến mại: '+safe(enr.discount_amount?money(enr.discount_amount):'Không')+'</div><div class="line"><b>Tổng học phí thực đóng: '+money(enr.final_price)+'</b></div><div class="line">Số tiền đặt cọc / đã nộp: '+money(totalPaid)+'</div><div class="line">Số tiền bằng chữ: ................................</div><div class="line">Số tiền học phí còn phải hoàn thành: '+money(remain)+'</div></div>'+
 '<div class="section">DANH MỤC CHƯƠNG TRÌNH ĐÀO TẠO</div><div class="line">• Tiếng Trung giao tiếp cơ bản – nâng cao</div><div class="line">• Tiếng Trung theo định hướng HSK 1–9</div><div class="line">• Tiếng Trung giao tiếp cho người đi làm</div><div class="line">• Tiếng Anh (giao tiếp, TOEIC, IELTS)</div><div class="line">• Tiếng Nhật, Tiếng Hàn và các chương trình ngoại ngữ khác theo kế hoạch đào tạo của Trung tâm.</div>'+
 '<div class="section">TƯ VẤN & XÁC NHẬN</div><div class="grid"><div class="line">Tư vấn viên: ................................</div><div class="line">Mã tư vấn viên: ................................</div><div class="line">Nhóm / Lớp: '+safe(cls)+'</div><div class="line">Ngày đăng ký: '+safe(new Date(p.paid_at).toLocaleDateString('vi-VN'))+'</div></div>'+
 '<div class="sign"><div><b>Học viên</b><br><br><br>(Ký và ghi rõ họ tên)</div><div><b>Giám đốc Trung tâm</b><br><br><br>(Ký và ghi rõ họ tên)</div></div></div></body></html>';
};
const buildReceiptHtml=(p:Payment,enr:Enrollment,allPayments:Payment[])=>{
 const student=enr.student?.full_name||'—',phone=enr.student?.phone||'—',email=enr.student?.email||'—',cls=enr.class?.name||'—',course=enr.class?.course||'—',branch=enr.class?.branch||enr.student?.branch||'—',no=p.id.slice(0,8).toUpperCase();
 const totalPaid=allPayments.filter(x=>x.enrollment_id===enr.id).reduce((a,x)=>a+Number(x.amount),0),remain=Math.max(0,Number(enr.final_price)-totalPaid);
 const safe=(v:any)=>String(v??'—').replace(/[&<>"]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[x]||x));
 const row=(l:string,v:any)=>'<div class="row"><b>'+l+'</b><span>'+safe(v)+'</span></div>';
 const head='<div class="head"><b>TRUNG TÂM NGOẠI NGỮ LIÊN HOA GLOBAL EDUCATION</b><div>KẾT NỐI TRI THỨC – MỞ LỐI TƯƠNG LAI</div></div>';
 return '<!doctype html><html lang="vi"><head><meta charset="utf-8"><title>Bộ hồ sơ '+safe(no)+'</title><style>body{font-family:Arial,sans-serif;color:#111;margin:0}.page{max-width:800px;margin:auto;padding:22mm 16mm;box-sizing:border-box;page-break-after:always}.page:last-child{page-break-after:auto}.head{text-align:center;font-size:14px;line-height:1.6}.title{text-align:center;font-size:20px;font-weight:700;margin:16px 0}.section{font-weight:700;font-size:15px;margin:14px 0 8px;padding-bottom:5px;border-bottom:1px solid #222}.row{display:grid;grid-template-columns:210px 1fr;border-bottom:1px dotted #999;padding:7px 0;line-height:1.35}.grid{display:grid;grid-template-columns:1fr 1fr;border:1px solid #999}.cell{padding:8px;border-right:1px solid #999;border-bottom:1px solid #999;min-height:22px}.box{border:1px solid #999;padding:10px;margin:10px 0}.course-table{width:100%;border-collapse:collapse;font-size:11px}.course-table th,.course-table td{border:1px solid #555;padding:7px;text-align:center;vertical-align:middle}.course-table th{font-weight:700}.sign{display:grid;grid-template-columns:1fr 1fr;text-align:center;margin-top:48px}.sign4{display:grid;grid-template-columns:repeat(4,1fr);text-align:center;margin-top:55px}.small{font-size:11px;line-height:1.55}.line{padding:6px 0;line-height:1.5}@media print{.page{padding:15mm 12mm}}</style></head><body>'+
 '<div class="page">'+head+'<div class="title">ĐƠN ĐĂNG KÝ NHẬP HỌC</div><div style="text-align:center">Trung tâm Ngoại ngữ Liên Hoa Global Education</div>'+
 '<div class="section">I. THÔNG TIN HỌC VIÊN</div><div class="grid"><div class="cell"><b>Họ và tên*:</b> '+safe(student)+'</div><div class="cell"><b>Ngày tháng năm sinh*:</b> '+safe(enr.student?.date_of_birth?new Date(enr.student.date_of_birth).toLocaleDateString('vi-VN'):'—')+'</div><div class="cell"><b>Giới tính:</b> '+safe(enr.student?.gender||'—')+'</div><div class="cell"><b>Số điện thoại*:</b> '+safe(phone)+'</div><div class="cell"><b>Email:</b> '+safe(email)+'</div><div class="cell" style="grid-column:1/3"><b>Địa chỉ:</b> '+safe(enr.student?.address||'—')+'</div></div>'+
 '<div class="section">II. THÔNG TIN KHÓA HỌC</div><div class="grid"><div class="cell"><b>Khóa học đăng ký:</b> '+safe(course)+'</div><div class="cell"><b>Lịch / ca học đăng ký:</b> ................................</div><div class="cell"><b>Ngày dự kiến bắt đầu:</b> '+safe(enr.class?.start_date||'—')+'</div><div class="cell"><b>Học viên vào học từ buổi thứ:</b> ................................</div><div class="cell" style="grid-column:1/3"><b>Nguồn biết thông tin:</b> ☐ Facebook &nbsp; ☐ Website &nbsp; ☐ Tư vấn trực tiếp &nbsp; ☐ Bạn bè &nbsp; ☐ Khác: ...............</div></div>'+
 '<div class="section">THÔNG TIN HỌC PHÍ – ĐĂNG KÝ KHÓA HỌC</div><table class="course-table"><thead><tr><th>Khóa học<br>(Trình độ)</th><th>Gói học phí<br>(Buổi/Tháng)</th><th>Thời gian học<br>dự kiến</th><th>Nguyên giá<br>(Giá gốc)</th><th>Chương trình<br>khuyến mại</th><th>Tổng học phí<br>thực đóng</th><th>Quà tặng/<br>Ghi chú</th></tr></thead><tbody><tr><td>'+safe(course)+'</td><td>................................</td><td>................................</td><td>'+money(enr.list_price)+'</td><td>'+money(enr.discount_amount)+'</td><td><b>'+money(enr.final_price)+'</b></td><td>'+safe(p.note||'')+'</td></tr><tr><td colspan="7" style="text-align:left">Số tiền đặt cọc: <b>'+money(totalPaid)+'</b></td></tr><tr><td colspan="7" style="text-align:left">Số tiền bằng chữ: ................................................................................................</td></tr><tr><td colspan="7" style="text-align:left">Số tiền học phí còn phải hoàn thành: <b>'+money(remain)+'</b></td></tr></tbody></table>'+
 '<div class="section">DANH MỤC CHƯƠNG TRÌNH ĐÀO TẠO</div><div class="line">• Tiếng Trung giao tiếp cơ bản – nâng cao</div><div class="line">• Tiếng Trung theo định hướng HSK 1–9</div><div class="line">• Tiếng Trung giao tiếp cho người đi làm</div><div class="line">• Tiếng Anh (giao tiếp, TOEIC, IELTS)</div><div class="line">• Tiếng Nhật, Tiếng Hàn và các chương trình ngoại ngữ khác theo kế hoạch đào tạo của Trung tâm.</div>'+
 '<div class="box small"><b>Cam kết sử dụng thông tin/hình ảnh:</b> Tôi đồng ý cho Trung tâm Ngoại ngữ Liên Hoa Global Education sử dụng thông tin và hình ảnh của tôi/con tôi cho mục đích truyền thông của Trung tâm, với điều kiện không gây ảnh hưởng bất lợi đến người học.<br>☐ Đồng ý &nbsp;&nbsp; ☐ Không đồng ý</div>'+
 '<div class="section">TƯ VẤN & XÁC NHẬN</div><div class="grid"><div class="cell">Tư vấn viên: ........................................................</div><div class="cell">Mã tư vấn viên: ........................................................</div><div class="cell">Nhóm / Lớp: '+safe(cls)+'</div><div class="cell">Ngày đăng ký: '+safe(new Date(p.paid_at).toLocaleDateString('vi-VN'))+'</div></div>'+
 '<div class="sign"><div><b>Học viên</b><br><br><br>(Ký và ghi rõ họ tên)</div><div><b>Giám đốc Trung tâm</b><br><br><br>(Ký và ghi rõ họ tên)</div></div></div>'+
 '<div class="page">'+head+'<div class="title">CHÍNH SÁCH VÀ QUY ĐỊNH CHUNG</div>'+
 '<div class="section">I. NỘI QUY LỚP HỌC</div><div class="line">• Học viên cần lên lớp đúng giờ và mang đầy đủ dụng cụ học tập, giáo trình, tài liệu và bút viết.</div><div class="line">• Học viên tuân thủ nội quy lớp học; không làm việc riêng, gây mất trật tự hoặc có hành vi thiếu tôn trọng giáo viên và học viên khác.</div><div class="line">• Học viên có trách nhiệm hoàn thành bài tập, tham gia các bài kiểm tra và bảo đảm số buổi học theo chương trình đã đăng ký.</div><div class="line">• Trường hợp vi phạm nội quy, giáo viên hoặc bộ phận quản lý lớp có quyền nhắc nhở và xử lý theo quy định của Trung tâm.</div>'+
 '<div class="section">II. CHÍNH SÁCH CHĂM SÓC HỌC VIÊN</div><div class="line">• Giáo viên / bộ phận phụ trách lớp theo dõi tiến trình học tập và cập nhật thông tin lớp học cho học viên.</div><div class="line">• Học viên có thể được hỗ trợ học bổ trợ khi có đề xuất chuyên môn phù hợp.</div><div class="line">• Trong trường hợp bất khả kháng như thiên tai, dịch bệnh hoặc điều kiện không bảo đảm tổ chức học trực tiếp, Trung tâm có thể chuyển sang hình thức học trực tuyến phù hợp.</div>'+
 '<div class="section">III. CHÍNH SÁCH HỌC PHÍ</div><b>1. Nhập học, ưu đãi, đặt cọc</b><div class="line">• Học viên hoàn thiện Đơn đăng ký nhập học và các thủ tục tài chính theo thông báo của Trung tâm để được xếp lớp.</div><div class="line">• Các chương trình ưu đãi chỉ được áp dụng khi học viên đáp ứng điều kiện và thời hạn của từng chương trình.</div><div class="line">• Mức học phí, tài liệu, quà tặng và các khoản thu khác được ghi nhận trên phiếu/đơn đăng ký hoặc thông báo học phí tại thời điểm đăng ký.</div></div>'+
 '<div class="page">'+head+'<div class="title">CHÍNH SÁCH BẢO LƯU – CHUYỂN LỚP – CHUYỂN NHƯỢNG</div>'+
 '<div class="section">2. Bảo lưu học phí</div><div class="line">• Việc bảo lưu được xem xét trong các trường hợp có lý do chính đáng hoặc bất khả kháng và phải được Trung tâm xác nhận.</div><div class="line">• Học viên cần thông báo và hoàn thiện thủ tục bảo lưu trước thời điểm nghỉ học theo quy định của Trung tâm.</div><div class="line">• Khi quay lại học, học viên có thể được kiểm tra/xác nhận trình độ để sắp xếp vào lớp phù hợp.</div><div class="line">• Thời hạn và điều kiện bảo lưu cụ thể được thực hiện theo chính sách học phí áp dụng tại thời điểm đăng ký.</div>'+
 '<div class="section">3. Chuyển lớp / thay đổi lịch học</div><div class="line">• Học viên có nhu cầu chuyển lớp cần liên hệ bộ phận phụ trách lớp để được xem xét theo tình trạng chỗ trống và trình độ.</div><div class="line">• Nếu lớp mới có mức học phí khác, phần chênh lệch (nếu có) được thực hiện theo chính sách của Trung tâm.</div><div class="line">• Việc thay đổi giáo trình do chuyển cấp độ được thực hiện theo chương trình đào tạo tương ứng.</div>'+
 '<div class="section">4. Chuyển nhượng học phí</div><div class="line">• Việc chuyển nhượng học phí chỉ được thực hiện khi được Trung tâm chấp thuận và đáp ứng các điều kiện tại thời điểm xử lý.</div><div class="line">• Hồ sơ chuyển nhượng phải có xác nhận của các bên liên quan và giấy tờ tùy thân hợp lệ.</div><div class="line">• Các chương trình khuyến mại, quà tặng hoặc quyền lợi có điều kiện có thể không được chuyển nhượng nếu chính sách chương trình quy định khác.</div></div>'+
 '<div class="page">'+head+'<div class="title">HOÀN TRẢ HỌC PHÍ – AN TOÀN HỌC VIÊN</div>'+
 '<div class="section">5. Hoàn trả học phí</div><div class="line">• Trung tâm xem xét hoàn trả học phí trong các trường hợp đặc biệt/bất khả kháng theo chính sách được công bố và hồ sơ thực tế.</div><div class="line">• Mức hoàn trả, chi phí hành chính (nếu có) và số học phí chưa sử dụng được xác định theo chính sách áp dụng tại thời điểm phát sinh.</div><div class="line">• Các khoản phí đã sử dụng, tài liệu hoặc quyền lợi đã cung cấp có thể được khấu trừ theo quy định.</div>'+
 '<div class="section">IV. QUY ĐỊNH VỀ ĐẢM BẢO AN TOÀN CHO HỌC VIÊN</div><div class="line">• Học viên tuân thủ quy định ra vào, di chuyển và sử dụng các khu vực thuộc Trung tâm.</div><div class="line">• Học viên không tự ý rời khỏi khu vực học tập trong thời gian buổi học nếu chưa thông báo cho giáo viên/bộ phận phụ trách.</div><div class="line">• Đối với học viên chưa đủ tuổi tự quản lý việc đi về, phụ huynh/người giám hộ phối hợp với Trung tâm trong việc đưa đón và bảo đảm an toàn.</div><div class="line">• Khi có sự cố liên quan đến an toàn trong khuôn viên Trung tâm, các bên phối hợp xử lý theo tình huống thực tế và quy định hiện hành.</div>'+
 '<div class="section">V. THÔNG TIN LIÊN HỆ</div><div class="grid"><div class="cell"><b>Tên đơn vị:</b></div><div class="cell">TRUNG TÂM NGOẠI NGỮ LIÊN HOA GLOBAL EDUCATION</div><div class="cell"><b>Địa chỉ cơ sở:</b></div><div class="cell">594 Nguyễn Trãi, phường Võ Cường, TP. Bắc Ninh</div><div class="cell"><b>Hotline:</b></div><div class="cell">........................................................</div><div class="cell"><b>Email / Website:</b></div><div class="cell">........................................................</div></div></div>'+
 '<div class="page">'+head+'<div class="title">XÁC NHẬN ĐĂNG KÝ NHẬP HỌC</div><p>Tôi xác nhận đã đọc, hiểu và đồng ý với các thông tin đăng ký, chính sách học phí và quy định của Trung tâm Ngoại ngữ Liên Hoa Global Education.</p><p>Các thông tin về khóa học, học phí, ưu đãi, giáo trình/tài liệu và quà tặng (nếu có) được xác nhận theo nội dung ghi tại Đơn đăng ký và thông báo của Trung tâm tại thời điểm đăng ký.</p><p style="text-align:right">...................., ngày ...... tháng ...... năm ........</p><div class="sign4"><div><b>Học viên</b><br><br><br>(Ký và ghi rõ họ tên)</div><div><b>Chuyên viên TVTS</b><br><br><br>(Ký và ghi rõ họ tên)</div><div><b>Kế toán Trung tâm</b><br><br><br>(Ký và ghi rõ họ tên)</div><div><b>Giám đốc Trung tâm</b><br><br><br>(Ký và ghi rõ họ tên)</div></div></div></body></html>';
};
const exportReceipt=(p:Payment,enr:Enrollment|undefined,allPayments:Payment[])=>{if(!enr)return;const html=buildReceiptHtml(p,enr,allPayments),blob=new Blob([html],{type:'text/html;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Bo_ho_so_Phu_thu_Don_dang_ky_'+p.id.slice(0,8).toUpperCase()+'.html';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)};
const printReceipt=(p:Payment,enr:Enrollment|undefined,allPayments:Payment[])=>{if(!enr)return;const html=buildReceiptHtml(p,enr,allPayments),w=window.open('','_blank');if(!w){alert('Hãy cho phép cửa sổ in (pop-up) cho CRM.');return}w.document.open();w.document.write(html);w.document.close();w.focus();setTimeout(()=>w.print(),500)};
const statusLabel:Record<string,string>={planned:'Dự kiến',active:'Đang học',completed:'Đã kết thúc',cancelled:'Đã hủy'};
const monthNow=()=>new Date().toISOString().slice(0,7);

function App(){
 const [session,setSession]=useState<any>(null); const [profile,setProfile]=useState<any>(null); const [classes,setClasses]=useState<ClassRow[]>([]); const [students,setStudents]=useState<Student[]>([]); const [enrollments,setEnrollments]=useState<Enrollment[]>([]); const [payments,setPayments]=useState<Payment[]>([]);
 const [page,setPage]=useState<'overview'|'classes'|'students'|'enrollments'|'payments'>('overview'); const [branch,setBranch]=useState('all'); const [query,setQuery]=useState(''); const [month,setMonth]=useState(monthNow());
 const [showClass,setShowClass]=useState(false); const [showStudent,setShowStudent]=useState(false); const [editingStudent,setEditingStudent]=useState<Student|null>(null); const [showEnrollment,setShowEnrollment]=useState(false); const [showPayment,setShowPayment]=useState(false); const [editingPayments,setEditingPayments]=useState<Payment[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 useEffect(()=>{if(!supabase){setLoading(false);return} supabase.auth.getSession().then(({data})=>setSession(data.session)); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(session?.user)load()},[session]);
 async function load(){if(!supabase||!session)return;setLoading(true);setError(''); const [p,c,s,e,pay]=await Promise.all([
   supabase.from('profiles').select('id,full_name,email,role,branch,active').eq('id',session.user.id).single(),
   supabase.from('classes').select('*').order('start_date',{ascending:false}),
   supabase.from('students').select('*').order('created_at',{ascending:false}),
   supabase.from('enrollments').select('*,student:students(*),class:classes(*)').order('enrolled_at',{ascending:false}),
   supabase.from('payments').select('*').order('paid_at',{ascending:false})
 ]); if(p.error){setError(p.error.message);await supabase.auth.signOut();return} if(!p.data?.active){setError('Tài khoản đã bị vô hiệu hóa.');await supabase.auth.signOut();return} if(c.error||s.error||e.error||pay.error)setError((c.error||s.error||e.error||pay.error)?.message||'Không tải được dữ liệu'); setProfile(p.data);setClasses(c.data||[]);setStudents(s.data||[]);setEnrollments(e.data||[]);setPayments(pay.data||[]);setLoading(false)}
 if(!supabase||!session)return <Login/>;
 if(profile?.role==='sale')return <AccessDenied/>;
 const monthPayments=payments.filter(p=>p.paid_at.slice(0,7)===month);
 const revenue=monthPayments.reduce((a,p)=>a+Number(p.amount),0);
 const contracted=enrollments.filter(e=>e.status!=='cancelled').reduce((a,e)=>a+Number(e.final_price),0);
 const paidAll=payments.reduce((a,p)=>a+Number(p.amount),0);
 const debt=Math.max(0,contracted-paidAll);
 const filteredStudents=students.filter(s=>(branch==='all'||s.branch===branch)&&[s.full_name,s.phone,s.email,s.branch].join(' ').toLowerCase().includes(query.toLowerCase()));
 const branchRevenue=(b:string)=>monthPayments.reduce((sum,p)=>{const e=enrollments.find(x=>x.id===p.enrollment_id);const c=e&&classes.find(x=>x.id===e.class_id);return sum+(c?.branch===b?Number(p.amount):0)},0);
 const debtOf=(e:Enrollment)=>{const paid=payments.filter(p=>p.enrollment_id===e.id).reduce((a,p)=>a+Number(p.amount),0);return Math.max(0,Number(e.final_price)-paid)};
 const deleteStudent=async(s:Student)=>{if(!['admin','director'].includes(profile?.role)||!supabase)return;if(!window.confirm(`Xóa học viên "${s.full_name}"? Thao tác này không thể hoàn tác.`))return;const linked=enrollments.some(e=>e.student_id===s.id);if(linked){alert('Không thể xóa học viên đã có đăng ký khóa học. Hãy kiểm tra/đóng các đăng ký trước.');return}const {error}=await supabase.from('students').delete().eq('id',s.id);if(error)alert(error.message);else load()};
 const scopedEnrollments=enrollments.filter(e=>branch==='all'||e.class?.branch===branch||e.student?.branch===branch);
 const scopedPayments=payments.filter(p=>{const e=enrollments.find(x=>x.id===p.enrollment_id);return branch==='all'||e?.class?.branch===branch||e?.student?.branch===branch;});
 return <div className="app"><aside><div className="brand"><div className="logo">LH</div><div><b>LIÊN HOA</b><small>GLOBAL EDUCATION</small></div></div><nav>
   <a onClick={()=>window.location.href=window.location.pathname}><ArrowLeft size={14}/> CRM chính</a><a className={page==='overview'?'active':''} onClick={()=>setPage('overview')}><WalletCards size={14}/> Tổng quan doanh thu</a><a className={page==='classes'?'active':''} onClick={()=>setPage('classes')}><GraduationCap size={14}/> Lớp học</a><a className={page==='students'?'active':''} onClick={()=>setPage('students')}><Building2 size={14}/> Học viên</a><a className={page==='enrollments'?'active':''} onClick={()=>setPage('enrollments')}><CheckCircle2 size={14}/> Đăng ký khóa học</a><a className={page==='payments'?'active':''} onClick={()=>setPage('payments')}><Banknote size={14}/> Phiếu thu</a>
 </nav><div className="side-foot"><div className="user"><Building2 size={14}/><span>{profile?.full_name}</span></div><small>{String(profile?.role||'').toUpperCase()} • THU HỌC PHÍ</small></div></aside>
 <main><header><div><h1>Thu học phí & Doanh thu</h1><p>Học viên • Lớp học • Giảm giá • Công nợ • Phiếu thu</p></div><div className="header-actions"><button className="icon-btn" onClick={load} disabled={loading}><RefreshCw size={17}/></button></div></header>{error&&<div className="error">{error}<button onClick={()=>setError('')}><X size={13}/></button></div>}
 {page==='overview'&&<><div className="filters"><label style={{fontSize:10,color:'#667085'}}>Kỳ doanh thu <input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><select value={branch} onChange={e=>setBranch(e.target.value)}><option value="all">Tất cả cơ sở</option><option>Bắc Ninh</option><option>Lạng Sơn</option></select></div><section className="cards"><Card label="Doanh thu đã thu" value={money(revenue)} note={`Trong ${month}`} icon={<Banknote/>}/><Card label="Doanh thu hợp đồng" value={money(contracted)} note="Sau giảm giá" icon={<CheckCircle2/>}/><Card label="Công nợ" value={money(debt)} note="Toàn bộ đăng ký" icon={<WalletCards/>}/><Card label="Học viên" value={String(students.length)} note={`${enrollments.length} lượt đăng ký`} icon={<GraduationCap/>}/></section><section className="cards"><Card label="Bắc Ninh" value={money(branchRevenue('Bắc Ninh'))} note={`Đã thu ${month}`} icon={<Building2/>}/><Card label="Lạng Sơn" value={money(branchRevenue('Lạng Sơn'))} note={`Đã thu ${month}`} icon={<Building2/>}/></section><section className="panel"><div className="panel-head"><div><h2>Đăng ký gần đây</h2><p>Giá gốc → giảm giá → phải thu → đã thu → còn nợ</p></div><div style={{display:'flex',gap:8}}><button className="primary" onClick={()=>setShowEnrollment(true)}><Plus size={15}/> Đăng ký học</button><button className="primary" onClick={()=>setShowPayment(true)}><Plus size={15}/> Thu học phí</button></div></div><EnrollmentTable enrollments={enrollments.slice(0,12)} payments={payments}/></section></>}
 {page==='classes'&&<section className="panel"><div className="panel-head"><div><h2>Danh sách lớp</h2><p>{classes.length} lớp</p></div><button className="primary" onClick={()=>setShowClass(true)}><Plus size={15}/> Thêm lớp</button></div><div className="branch-tabs"><button className={branch==='all'?'active':''} onClick={()=>setBranch('all')}>Tất cả</button><button className={branch==='Bắc Ninh'?'active':''} onClick={()=>setBranch('Bắc Ninh')}>Bắc Ninh</button><button className={branch==='Lạng Sơn'?'active':''} onClick={()=>setBranch('Lạng Sơn')}>Lạng Sơn</button></div><div className="table-wrap"><table><thead><tr><th>Lớp</th><th>Khóa học</th><th>Cơ sở</th><th>Giảng viên</th><th>Thời gian</th><th>Học phí</th><th>Trạng thái</th></tr></thead><tbody>{classes.filter(c=>branch==='all'||c.branch===branch).map(c=><tr key={c.id}><td><b>{c.name}</b></td><td>{c.course||'—'}</td><td>{c.branch}</td><td>{c.teacher_name||'—'}</td><td>{c.start_date||'—'} → {c.end_date||'—'}</td><td>{money(c.list_tuition)}</td><td><span className="role-pill">{statusLabel[c.status]||c.status}</span></td></tr>)}</tbody></table></div></section>}
 {page==='students'&&<section className="panel"><div className="panel-head"><div><h2>Học viên</h2><p>{filteredStudents.length} học viên</p></div><div style={{display:'flex',gap:8}}><button className="primary" onClick={()=>{setEditingStudent(null);setShowStudent(true)}}><Plus size={15}/> Thêm học viên</button><button className="primary" onClick={()=>setShowEnrollment(true)}><Plus size={15}/> Đăng ký học</button></div></div><div className="branch-tabs"><button className={branch==='all'?'active':''} onClick={()=>setBranch('all')}>Tất cả</button><button className={branch==='Bắc Ninh'?'active':''} onClick={()=>setBranch('Bắc Ninh')}>Bắc Ninh</button><button className={branch==='Lạng Sơn'?'active':''} onClick={()=>setBranch('Lạng Sơn')}>Lạng Sơn</button></div><div className="filters"><div className="search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm tên, SĐT, email..."/></div></div><div className="table-wrap"><table><thead><tr><th>Học viên</th><th>SĐT</th><th>Email</th><th>Cơ sở</th><th>Đăng ký</th><th>Phải thu</th><th>Đã thu</th><th>Còn nợ</th>{(profile?.role==='admin'||profile?.role==='director')&&<th>Thao tác</th>}</tr></thead><tbody>{filteredStudents.map(s=>{const es=enrollments.filter(e=>e.student_id===s.id);const due=es.reduce((a,e)=>a+Number(e.final_price),0);const paid=es.reduce((a,e)=>a+payments.filter(p=>p.enrollment_id===e.id).reduce((x,p)=>x+Number(p.amount),0),0);return <tr key={s.id}><td><b>{s.full_name}</b></td><td>{s.phone||'—'}</td><td>{s.email||'—'}</td><td>{s.branch||'—'}</td><td>{es.length}</td><td>{money(due)}</td><td><div style={{display:'flex',alignItems:'center',gap:6}}>{money(paid)}{(profile?.role==='admin'||profile?.role==='director')&&paid>0&&<button className="table-action" title="Chỉnh sửa các khoản đã thu" onClick={()=>setEditingPayments(payments.filter(p=>es.some(e=>e.id===p.enrollment_id)))}><Pencil size={13}/></button>}</div></td><td>{money(Math.max(0,due-paid))}</td>{(profile?.role==='admin'||profile?.role==='director')&&<td><div className="row-actions"><button className="table-action" title="Sửa học viên" onClick={()=>{setEditingStudent(s);setShowStudent(true)}}><Pencil size={14}/></button><button className="table-action danger" title="Xóa học viên" onClick={()=>deleteStudent(s)}><Trash2 size={14}/></button></div></td>}</tr>})}</tbody></table></div></section>}
 {page==='enrollments'&&<section className="panel"><div className="panel-head"><div><h2>Đăng ký khóa học</h2><p>{scopedEnrollments.length} lượt đăng ký • {branch==='all'?'Tất cả':branch}</p></div><button className="primary" onClick={()=>setShowEnrollment(true)}><Plus size={15}/> Đăng ký học</button></div><EnrollmentTable enrollments={scopedEnrollments} payments={payments}/></section>}
 {page==='payments'&&<section className="panel"><div className="panel-head"><div><h2>Phiếu thu học phí</h2><p>{scopedPayments.length} giao dịch • {branch==='all'?'Tất cả':branch}</p></div><button className="primary" onClick={()=>setShowPayment(true)}><Plus size={15}/> Ghi nhận thu tiền</button></div><div className="table-wrap"><table><thead><tr><th>Ngày thu</th><th>Học viên</th><th>Lớp</th><th>Số tiền</th><th>Phương thức</th><th>Mã giao dịch</th><th>Ghi chú</th><th>Xuất file</th><th>In</th></tr></thead><tbody>{scopedPayments.map(p=>{const e=enrollments.find(x=>x.id===p.enrollment_id);return <tr key={p.id}><td>{new Date(p.paid_at).toLocaleString('vi-VN')}</td><td>{e?.student?.full_name||'—'}</td><td>{e?.class?.name||'—'}</td><td><b>{money(p.amount)}</b></td><td>{methodLabel[p.method]||p.method}</td><td>{p.reference||'—'}</td><td>{p.note||'—'}</td><td><button className="table-action" title="Xuất file phiếu thu" onClick={()=>exportReceipt(p,e,payments)}>Xuất</button></td><td><button className="table-action" title="In phiếu thu + đơn đăng ký" onClick={()=>printReceipt(p,e,payments)}>In</button></td></tr>})}</tbody></table></div></section>}
 </main>{editingPayments.length>0&&<PaymentHistoryModal payments={editingPayments} enrollments={enrollments} onClose={()=>setEditingPayments([])} onSaved={()=>{setEditingPayments([]);load()}}/>}{showClass&&<ClassModal onClose={()=>setShowClass(false)} onSaved={load}/>} {showStudent&&<StudentModal student={editingStudent} canEdit={['admin','director'].includes(profile?.role)} onClose={()=>{setShowStudent(false);setEditingStudent(null)}} onSaved={load}/>} {showEnrollment&&<EnrollmentModal students={students} classes={classes} onCreateClass={()=>setShowClass(true)} onClose={()=>setShowEnrollment(false)} onSaved={load}/>}  {showPayment&&<PaymentModal enrollments={enrollments} payments={payments} onClose={()=>setShowPayment(false)} onSaved={load}/>}</div>
}
function Login(){return <div className="login"><div className="login-card"><div className="logo big">LH</div><h1>Thu học phí</h1><p>Phiên đăng nhập CRM không còn hoạt động.</p><button className="primary full" onClick={()=>window.location.href=window.location.pathname}>Quay lại CRM</button></div></div>}
function AccessDenied(){return <div className="login"><div className="login-card"><div className="logo big">LH</div><h1>Thu học phí</h1><p>Tài khoản Sale chưa có quyền quản trị thu học phí.</p><button className="primary full" onClick={()=>window.location.href=window.location.pathname}>Quay lại CRM</button></div></div>}
function Card({label,value,note,icon}:{label:string;value:string;note:string;icon:React.ReactNode}){return <div className="card"><div className="card-icon">{icon}</div><div className="label">{label}</div><div className="value">{value}</div><div className="note">{note}</div></div>}
function EnrollmentTable({enrollments,payments}:{enrollments:Enrollment[];payments:Payment[]}){return <div className="table-wrap"><table><thead><tr><th>Học viên</th><th>Lớp</th><th>Cơ sở</th><th>Giá gốc</th><th>Giảm</th><th>Phải thu</th><th>Đã thu</th><th>Còn nợ</th></tr></thead><tbody>{enrollments.map(e=>{const paid=payments.filter(p=>p.enrollment_id===e.id).reduce((a,p)=>a+Number(p.amount),0);return <tr key={e.id}><td><b>{e.student?.full_name||'—'}</b><small>{e.student?.phone||'—'}</small></td><td>{e.class?.name||'—'}</td><td>{e.class?.branch||e.student?.branch||'—'}</td><td>{money(e.list_price)}</td><td>{money(e.discount_amount)}</td><td>{money(e.final_price)}</td><td>{money(paid)}</td><td>{money(Math.max(0,Number(e.final_price)-paid))}</td></tr>})}</tbody></table></div>}
function ClassModal({onClose,onSaved}:{onClose:()=>void;onSaved:()=>void}){async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;const f=new FormData(e.currentTarget);const {error}=await supabase.from('classes').insert({name:f.get('name'),course:f.get('course')||null,branch:f.get('branch'),teacher_name:f.get('teacher_name')||null,start_date:f.get('start_date')||null,end_date:f.get('end_date')||null,total_sessions:Number(f.get('total_sessions')||0)||null,list_tuition:Number(f.get('list_tuition')||0),status:f.get('status')});if(error)alert(error.message);else{onClose();onSaved()}}return <Modal title="Thêm lớp học" onClose={onClose}><form onSubmit={submit}><input name="name" required placeholder="Tên lớp, ví dụ: Giao tiếp Trung cơ bản K10"/><select name="course" defaultValue=""><option value="">Chọn khóa học</option><option value="HSK 1">HSK 1</option><option value="HSK 2">HSK 2</option><option value="HSK 3">HSK 3</option><option value="HSK 4">HSK 4</option><option value="HSK 5">HSK 5</option><option value="HSK 6">HSK 6</option><option value="HSK 7">HSK 7</option><option value="HSK 8">HSK 8</option><option value="HSK 9">HSK 9</option><option value="HSK 1–3">HSK 1–3</option><option value="HSK 1–4">HSK 1–4</option><option value="HSK 1–6">HSK 1–6</option><option value="HSK 1–9">HSK 1–9</option><option value="Giao tiếp Cơ bản">Giao tiếp Cơ bản</option><option value="Giao tiếp Trung cấp / Thực chiến">Giao tiếp Trung cấp / Thực chiến</option><option value="Giao tiếp Nâng cao / Thương mại">Giao tiếp Nâng cao / Thương mại</option><option value="Combo Cơ bản → Nâng cao">Combo Cơ bản → Nâng cao</option></select><select name="branch"><option>Bắc Ninh</option><option>Lạng Sơn</option></select><input name="teacher_name" placeholder="Tên giảng viên"/><div className="form-grid"><label>Ngày bắt đầu<input name="start_date" type="date"/></label><label>Ngày kết thúc<input name="end_date" type="date"/></label></div><div className="form-grid"><input name="total_sessions" type="number" placeholder="Số buổi"/><input name="list_tuition" type="number" placeholder="Học phí niêm yết"/></div><select name="status"><option value="planned">Dự kiến</option><option value="active">Đang học</option><option value="completed">Đã kết thúc</option><option value="cancelled">Đã hủy</option></select><div className="modal-actions"><button type="button" onClick={onClose}>Hủy</button><button className="primary">Lưu lớp</button></div></form></Modal>}
function StudentModal({student,canEdit,onClose,onSaved}:{student:Student|null;canEdit:boolean;onClose:()=>void;onSaved:()=>void}){async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;const f=new FormData(e.currentTarget);const payload={full_name:String(f.get('full_name')||'').trim(),phone:f.get('phone')||null,email:f.get('email')||null,branch:f.get('branch'),date_of_birth:f.get('date_of_birth')||null,gender:f.get('gender')||null,address:f.get('address')||null};const result=student&&canEdit?await supabase.from('students').update(payload).eq('id',student.id):await supabase.from('students').insert(payload);if(result.error)alert(result.error.message);else{onClose();onSaved()}}return <Modal title={student?'Sửa thông tin học viên':'Thêm học viên'} onClose={onClose}><form onSubmit={submit}><input name="full_name" required defaultValue={student?.full_name||''} placeholder="Họ và tên"/><div className="form-grid"><label>Ngày tháng năm sinh<input name="date_of_birth" type="date" defaultValue={student?.date_of_birth||''}/></label><label>Giới tính<select name="gender" defaultValue={student?.gender||''}><option value="">Chọn giới tính</option><option>Nam</option><option>Nữ</option><option>Khác</option></select></label></div><input name="phone" defaultValue={student?.phone||''} placeholder="Số điện thoại"/><input name="email" type="email" defaultValue={student?.email||''} placeholder="Email"/><input name="address" defaultValue={student?.address||''} placeholder="Địa chỉ"/><select name="branch" defaultValue={student?.branch||'Bắc Ninh'}><option>Bắc Ninh</option><option>Lạng Sơn</option></select><div className="modal-actions"><button type="button" onClick={onClose}>Hủy</button><button className="primary">{student?'Lưu thay đổi':'Lưu học viên'}</button></div></form></Modal>}
function EnrollmentModal({students,classes,onCreateClass,onClose,onSaved}:{students:Student[];classes:ClassRow[];onCreateClass:()=>void;onClose:()=>void;onSaved:()=>void}){const [classId,setClassId]=useState('');const selected=classes.find(c=>c.id===classId);const [discount,setDiscount]=useState('0');const [discountType,setDiscountType]=useState<'vnd'|'percent'>('vnd');const list=Number(selected?.list_tuition||0);const discountValue=Number(discount||0);const discountAmount=discountType==='percent'?Math.min(list,list*discountValue/100):Math.min(list,discountValue);const final=Math.max(0,list-discountAmount);async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase||!selected)return;const f=new FormData(e.currentTarget);const {error}=await supabase.from('enrollments').insert({student_id:f.get('student_id'),class_id:classId,list_price:list,discount_amount:discountAmount,discount_type:discountType,discount_percent:discountType==='percent'?discountValue:0,final_price:final,status:'active',note:f.get('note')||null});if(error)alert(error.message);else{onClose();onSaved()}}return <Modal title="Đăng ký học viên vào lớp" onClose={onClose}><form onSubmit={submit}><select name="student_id" required><option value="">Chọn học viên</option>{students.map(s=><option key={s.id} value={s.id}>{s.full_name} • {s.phone||'—'} • {s.branch||'—'}</option>)}</select><div style={{display:'flex',gap:8,alignItems:'center'}}><select style={{flex:1}} value={classId} onChange={e=>setClassId(e.target.value)} required><option value="">{classes.filter(c=>c.status!=='cancelled').length?'Chọn lớp':'Chưa có lớp — hãy tạo lớp'}</option>{classes.filter(c=>c.status!=='cancelled').map(c=><option key={c.id} value={c.id}>{c.name} • {c.branch} • {money(c.list_tuition)}</option>)}</select><button type="button" className="secondary" onClick={onCreateClass}>+ Tạo lớp</button></div><div className="form-grid"><label>Giá niêm yết<input value={money(list)} readOnly/></label><label>Hình thức giảm<select value={discountType} onChange={e=>setDiscountType(e.target.value as 'vnd'|'percent')}><option value="vnd">Giảm theo VNĐ</option><option value="percent">Giảm theo %</option></select></label></div><div className="form-grid"><label>{discountType==='percent'?'Mức giảm (%)':'Mức giảm (VNĐ)'}<input type="number" min="0" max={discountType==='percent'?100:list} value={discount} onChange={e=>setDiscount(e.target.value)}/></label><label>Tiền giảm<input value={money(discountAmount)} readOnly/></label></div><label>Học phí phải thu<input value={final} readOnly/></label><textarea name="note" placeholder="Ghi chú giảm giá / chính sách"></textarea><div className="modal-actions"><button type="button" onClick={onClose}>Hủy</button><button className="primary" disabled={!classId}>Lưu đăng ký</button></div></form></Modal>}
function PaymentHistoryModal({payments,enrollments,onClose,onSaved}:{payments:Payment[];enrollments:Enrollment[];onClose:()=>void;onSaved:()=>void}){const [editing,setEditing]=useState<Payment|null>(null);const [saving,setSaving]=useState(false);const roleOk=['admin','director'].includes((window as any).__lhRole||'');const update=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!supabase||!editing)return;setSaving(true);const f=new FormData(e.currentTarget);const amount=Number(f.get('amount')||0);if(amount<=0){alert('Số tiền phải lớn hơn 0.');setSaving(false);return}const {data:all}=await supabase.from('payments').select('id,enrollment_id,amount').eq('enrollment_id',editing.enrollment_id);const others=(all||[]).filter((p:any)=>p.id!==editing.id).reduce((a:any,p:any)=>a+Number(p.amount),0);const enr=enrollments.find(x=>x.id===editing.enrollment_id);if(enr&&others+amount>Number(enr.final_price)){alert('Tổng số tiền đã thu không được vượt học phí phải thu.');setSaving(false);return}const {error}=await supabase.from('payments').update({amount,paid_at:new Date(String(f.get('paid_at'))).toISOString(),method:f.get('method'),reference:f.get('reference')||null,note:f.get('note')||null}).eq('id',editing.id);if(error)alert(error.message);else{setEditing(null);onSaved()}setSaving(false)};return <Modal title="Chỉnh sửa học phí đã thu" onClose={onClose}><p className="demo-note">Có {payments.length} phiếu thu. Chọn phiếu cần chỉnh sửa:</p>{payments.map(p=><div key={p.id} style={{display:'flex',justifyContent:'space-between',alignItems:'center',padding:'10px 0',borderBottom:'1px solid #eee'}}><div><b>{money(p.amount)}</b><div style={{fontSize:12,color:'#667085'}}>{new Date(p.paid_at).toLocaleString('vi-VN')} • {methodLabel[p.method]||p.method}</div></div><button type="button" className="table-action" onClick={()=>setEditing(p)}><Pencil size={14}/></button></div>)}{editing&&<form onSubmit={update} style={{marginTop:14}}><input name="amount" type="number" min="1" defaultValue={editing.amount} required placeholder="Số tiền đã thu"/><input name="paid_at" type="datetime-local" defaultValue={new Date(new Date(editing.paid_at).getTime()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16)}/><select name="method" defaultValue={editing.method}><option value="bank_transfer">Chuyển khoản</option><option value="qr">QR</option><option value="cash">Tiền mặt</option><option value="card">Thẻ</option><option value="other">Khác</option></select><input name="reference" defaultValue={editing.reference||''} placeholder="Mã giao dịch / nội dung chuyển khoản"/><textarea name="note" defaultValue={editing.note||''} placeholder="Ghi chú"></textarea><div className="modal-actions"><button type="button" onClick={()=>setEditing(null)}>Hủy</button><button className="primary" disabled={saving}>Lưu thay đổi</button></div></form>}</Modal>}
function PaymentModal({enrollments,payments,onClose,onSaved}:{enrollments:Enrollment[];payments:Payment[];onClose:()=>void;onSaved:()=>void}){const [enrollmentId,setEnrollmentId]=useState('');const selected=enrollments.find(e=>e.id===enrollmentId);const paid=selected?payments.filter(p=>p.enrollment_id===selected.id).reduce((a,p)=>a+Number(p.amount),0):0;const debt=selected?Math.max(0,Number(selected.final_price)-paid):0;async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase||!selected)return;const f=new FormData(e.currentTarget);const amount=Number(f.get('amount')||0);if(amount<=0||amount>debt){alert(`Số tiền thu phải lớn hơn 0 và không vượt công nợ ${money(debt)}.`);return}const raw=String(f.get('paid_at')||'');const {data:user}=await supabase.auth.getUser();const {error}=await supabase.from('payments').insert({enrollment_id:enrollmentId,amount,paid_at:raw?new Date(raw).toISOString():new Date().toISOString(),method:f.get('method'),reference:f.get('reference')||null,note:f.get('note')||null,received_by:user.user?.id||null});if(error)alert(error.message);else{onClose();onSaved()}}return <Modal title="Ghi nhận thu học phí" onClose={onClose}><form onSubmit={submit}><select value={enrollmentId} onChange={e=>setEnrollmentId(e.target.value)} required><option value="">Chọn học viên / lớp</option>{enrollments.filter(e=>e.status!=='cancelled').map(e=>{const p=payments.filter(x=>x.enrollment_id===e.id).reduce((a,x)=>a+Number(x.amount),0);return <option key={e.id} value={e.id}>{e.student?.full_name} • {e.class?.name} • Còn {money(Math.max(0,Number(e.final_price)-p))}</option>})}</select>{selected&&<div className="demo-note">Phải thu: <b>{money(selected.final_price)}</b> • Đã thu: <b>{money(paid)}</b> • Còn nợ: <b>{money(debt)}</b></div>}<input name="amount" type="number" min="1" max={debt||undefined} required placeholder="Số tiền thu"/><input name="paid_at" type="datetime-local" defaultValue={new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16)}/><select name="method"><option value="bank_transfer">Chuyển khoản</option><option value="qr">QR</option><option value="cash">Tiền mặt</option><option value="card">Thẻ</option><option value="other">Khác</option></select><input name="reference" placeholder="Mã giao dịch / nội dung chuyển khoản"/><textarea name="note" placeholder="Ghi chú"></textarea><div className="modal-actions"><button type="button" onClick={onClose}>Hủy</button><button className="primary" disabled={!selected||debt<=0}>Lưu phiếu thu</button></div></form></Modal>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="modal-backdrop"><div className="modal"><div className="modal-title"><div><h2>{title}</h2></div><button className="close-btn" onClick={onClose}><X size={15}/></button></div>{children}</div></div>}
createRoot(document.getElementById('root')!).render(<App/>);
