import React, { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Banknote, Building2, CheckCircle2, GraduationCap, Pencil, Plus, RefreshCw, Search, Trash2, WalletCards, X } from 'lucide-react';
import { createRoot } from 'react-dom/client';
import { supabase } from './lib/supabase';
import './styles.css';

type ClassRow={id:string;name:string;course:string|null;branch:string;teacher_name:string|null;start_date:string|null;end_date:string|null;total_sessions:number|null;list_tuition:number;status:string};
type Student={id:string;full_name:string;phone:string|null;email:string|null;branch:string|null;lead_id:string|null;created_at:string};
type Enrollment={id:string;student_id:string;class_id:string;list_price:number;discount_amount:number;final_price:number;status:string;enrolled_at:string;student?:Student;class?:ClassRow};
type Payment={id:string;enrollment_id:string;amount:number;paid_at:string;method:string;reference:string|null;note:string|null;received_by:string|null};
const money=(n:number)=>new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND',maximumFractionDigits:0}).format(Number(n)||0);
const methodLabel:Record<string,string>={cash:'Tiền mặt',bank_transfer:'Chuyển khoản',qr:'QR',card:'Thẻ',other:'Khác'};
const statusLabel:Record<string,string>={planned:'Dự kiến',active:'Đang học',completed:'Đã kết thúc',cancelled:'Đã hủy'};
const monthNow=()=>new Date().toISOString().slice(0,7);

function App(){
 const [session,setSession]=useState<any>(null); const [profile,setProfile]=useState<any>(null); const [classes,setClasses]=useState<ClassRow[]>([]); const [students,setStudents]=useState<Student[]>([]); const [enrollments,setEnrollments]=useState<Enrollment[]>([]); const [payments,setPayments]=useState<Payment[]>([]);
 const [page,setPage]=useState<'overview'|'classes'|'students'|'enrollments'|'payments'>('overview'); const [branch,setBranch]=useState('all'); const [query,setQuery]=useState(''); const [month,setMonth]=useState(monthNow());
 const [showClass,setShowClass]=useState(false); const [showStudent,setShowStudent]=useState(false); const [editingStudent,setEditingStudent]=useState<Student|null>(null); const [showEnrollment,setShowEnrollment]=useState(false); const [showPayment,setShowPayment]=useState(false); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 useEffect(()=>{if(!supabase){setLoading(false);return} supabase.auth.getSession().then(({data})=>setSession(data.session)); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(session?.user)load()},[session]);
 async function load(){if(!supabase||!session)return;setLoading(true);setError(''); const [p,c,s,e,pay]=await Promise.all([
   supabase.from('profiles').select('id,full_name,email,role,branch,active').eq('id',session.user.id).single(),
   supabase.from('classes').select('*').order('start_date',{ascending:false}),
   supabase.from('students').select('*').order('created_at',{ascending:false}),
   supabase.from('enrollments').select('*,student:students(*),class:classes(*)').order('enrolled_at',{ascending:false}),
   supabase.from('payments').select('*').order('paid_at',{ascending:false})
 ]); if(p.error){setError(p.error.message);await supabase.auth.signOut();return} if(!p.data?.active){setError('Tài khoản đã bị vô hiệu hóa.');await supabase.auth.signOut();return} if(c.error||s.error||e.error||pay.error)setError((c.error||s.error||e.error||pay.error)?.message||'Không tải được dữ liệu'); setProfile(p.data);setClasses(c.data||[]);setStudents(s.data||[]);setEnrollments(e.data||[]);setPayments(pay.data||[]);setLoading(false)}
 if(!supabase||!session)return <Login/>;
 if(profile?.role==='sale')return <AccessDenied/>;
 const monthPayments=payments.filter(p=>p.paid_at.slice(0,7)===month);
 const revenue=monthPayments.reduce((a,p)=>a+Number(p.amount),0);
 const contracted=enrollments.filter(e=>e.status!=='cancelled').reduce((a,e)=>a+Number(e.final_price),0);
 const paidAll=payments.reduce((a,p)=>a+Number(p.amount),0);
 const debt=Math.max(0,contracted-paidAll);
 const filteredStudents=students.filter(s=>(branch==='all'||s.branch===branch)&&[s.full_name,s.phone,s.email,s.branch].join(' ').toLowerCase().includes(query.toLowerCase()));
 const branchRevenue=(b:string)=>monthPayments.reduce((sum,p)=>{const e=enrollments.find(x=>x.id===p.enrollment_id);const c=e&&classes.find(x=>x.id===e.class_id);return sum+(c?.branch===b?Number(p.amount):0)},0);
 const debtOf=(e:Enrollment)=>{const paid=payments.filter(p=>p.enrollment_id===e.id).reduce((a,p)=>a+Number(p.amount),0);return Math.max(0,Number(e.final_price)-paid)};
 const deleteStudent=async(s:Student)=>{if(!['admin','director'].includes(profile?.role)||!supabase)return;if(!window.confirm(`Xóa học viên "${s.full_name}"? Thao tác này không thể hoàn tác.`))return;const linked=enrollments.some(e=>e.student_id===s.id);if(linked){alert('Không thể xóa học viên đã có đăng ký khóa học. Hãy kiểm tra/đóng các đăng ký trước.');return}const {error}=await supabase.from('students').delete().eq('id',s.id);if(error)alert(error.message);else load()};
 const scopedEnrollments=enrollments.filter(e=>branch==='all'||e.class?.branch===branch||e.student?.branch===branch);
 const scopedPayments=payments.filter(p=>{const e=enrollments.find(x=>x.id===p.enrollment_id);return branch==='all'||e?.class?.branch===branch||e?.student?.branch===branch;});
 return <div className="app"><aside><div className="brand"><div className="logo">LH</div><div><b>LIÊN HOA</b><small>GLOBAL EDUCATION</small></div></div><nav>
   <a onClick={()=>window.location.href=window.location.pathname}><ArrowLeft size={14}/> CRM chính</a><a className={page==='overview'?'active':''} onClick={()=>setPage('overview')}><WalletCards size={14}/> Tổng quan doanh thu</a><a className={page==='classes'?'active':''} onClick={()=>setPage('classes')}><GraduationCap size={14}/> Lớp học</a><a className={page==='students'?'active':''} onClick={()=>setPage('students')}><Building2 size={14}/> Học viên</a><a className={page==='enrollments'?'active':''} onClick={()=>setPage('enrollments')}><CheckCircle2 size={14}/> Đăng ký khóa học</a><a className={page==='payments'?'active':''} onClick={()=>setPage('payments')}><Banknote size={14}/> Phiếu thu</a>
 </nav><div className="side-foot"><div className="user"><Building2 size={14}/><span>{profile?.full_name}</span></div><small>{String(profile?.role||'').toUpperCase()} • THU HỌC PHÍ</small></div></aside>
 <main><header><div><h1>Thu học phí & Doanh thu</h1><p>Học viên • Lớp học • Giảm giá • Công nợ • Phiếu thu</p></div><div className="header-actions"><button className="icon-btn" onClick={load} disabled={loading}><RefreshCw size={17}/></button></div></header>{error&&<div className="error">{error}<button onClick={()=>setError('')}><X size={13}/></button></div>}
 {page==='overview'&&<><div className="filters"><label style={{fontSize:10,color:'#667085'}}>Kỳ doanh thu <input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><select value={branch} onChange={e=>setBranch(e.target.value)}><option value="all">Tất cả cơ sở</option><option>Bắc Ninh</option><option>Lạng Sơn</option></select></div><section className="cards"><Card label="Doanh thu đã thu" value={money(revenue)} note={`Trong ${month}`} icon={<Banknote/>}/><Card label="Doanh thu hợp đồng" value={money(contracted)} note="Sau giảm giá" icon={<CheckCircle2/>}/><Card label="Công nợ" value={money(debt)} note="Toàn bộ đăng ký" icon={<WalletCards/>}/><Card label="Học viên" value={String(students.length)} note={`${enrollments.length} lượt đăng ký`} icon={<GraduationCap/>}/></section><section className="cards"><Card label="Bắc Ninh" value={money(branchRevenue('Bắc Ninh'))} note={`Đã thu ${month}`} icon={<Building2/>}/><Card label="Lạng Sơn" value={money(branchRevenue('Lạng Sơn'))} note={`Đã thu ${month}`} icon={<Building2/>}/></section><section className="panel"><div className="panel-head"><div><h2>Đăng ký gần đây</h2><p>Giá gốc → giảm giá → phải thu → đã thu → còn nợ</p></div><div style={{display:'flex',gap:8}}><button className="primary" onClick={()=>setShowEnrollment(true)}><Plus size={15}/> Đăng ký học</button><button className="primary" onClick={()=>setShowPayment(true)}><Plus size={15}/> Thu học phí</button></div></div><EnrollmentTable enrollments={enrollments.slice(0,12)} payments={payments}/></section></>}
 {page==='classes'&&<section className="panel"><div className="panel-head"><div><h2>Danh sách lớp</h2><p>{classes.length} lớp</p></div><button className="primary" onClick={()=>setShowClass(true)}><Plus size={15}/> Thêm lớp</button></div><div className="branch-tabs"><button className={branch==='all'?'active':''} onClick={()=>setBranch('all')}>Tất cả</button><button className={branch==='Bắc Ninh'?'active':''} onClick={()=>setBranch('Bắc Ninh')}>Bắc Ninh</button><button className={branch==='Lạng Sơn'?'active':''} onClick={()=>setBranch('Lạng Sơn')}>Lạng Sơn</button></div><div className="table-wrap"><table><thead><tr><th>Lớp</th><th>Khóa học</th><th>Cơ sở</th><th>Giảng viên</th><th>Thời gian</th><th>Học phí</th><th>Trạng thái</th></tr></thead><tbody>{classes.filter(c=>branch==='all'||c.branch===branch).map(c=><tr key={c.id}><td><b>{c.name}</b></td><td>{c.course||'—'}</td><td>{c.branch}</td><td>{c.teacher_name||'—'}</td><td>{c.start_date||'—'} → {c.end_date||'—'}</td><td>{money(c.list_tuition)}</td><td><span className="role-pill">{statusLabel[c.status]||c.status}</span></td></tr>)}</tbody></table></div></section>}
 {page==='students'&&<section className="panel"><div className="panel-head"><div><h2>Học viên</h2><p>{filteredStudents.length} học viên</p></div><div style={{display:'flex',gap:8}}><button className="primary" onClick={()=>{setEditingStudent(null);setShowStudent(true)}}><Plus size={15}/> Thêm học viên</button><button className="primary" onClick={()=>setShowEnrollment(true)}><Plus size={15}/> Đăng ký học</button></div></div><div className="branch-tabs"><button className={branch==='all'?'active':''} onClick={()=>setBranch('all')}>Tất cả</button><button className={branch==='Bắc Ninh'?'active':''} onClick={()=>setBranch('Bắc Ninh')}>Bắc Ninh</button><button className={branch==='Lạng Sơn'?'active':''} onClick={()=>setBranch('Lạng Sơn')}>Lạng Sơn</button></div><div className="filters"><div className="search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm tên, SĐT, email..."/></div></div><div className="table-wrap"><table><thead><tr><th>Học viên</th><th>SĐT</th><th>Email</th><th>Cơ sở</th><th>Đăng ký</th><th>Phải thu</th><th>Đã thu</th><th>Còn nợ</th>{(profile?.role==='admin'||profile?.role==='director')&&<th>Thao tác</th>}</tr></thead><tbody>{filteredStudents.map(s=>{const es=enrollments.filter(e=>e.student_id===s.id);const due=es.reduce((a,e)=>a+Number(e.final_price),0);const paid=es.reduce((a,e)=>a+payments.filter(p=>p.enrollment_id===e.id).reduce((x,p)=>x+Number(p.amount),0),0);return <tr key={s.id}><td><b>{s.full_name}</b></td><td>{s.phone||'—'}</td><td>{s.email||'—'}</td><td>{s.branch||'—'}</td><td>{es.length}</td><td>{money(due)}</td><td>{money(paid)}</td><td>{money(Math.max(0,due-paid))}</td>{(profile?.role==='admin'||profile?.role==='director')&&<td><div className="row-actions"><button className="table-action" title="Sửa học viên" onClick={()=>{setEditingStudent(s);setShowStudent(true)}}><Pencil size={14}/></button><button className="table-action danger" title="Xóa học viên" onClick={()=>deleteStudent(s)}><Trash2 size={14}/></button></div></td>}</tr>})}</tbody></table></div></section>}
 {page==='enrollments'&&<section className="panel"><div className="panel-head"><div><h2>Đăng ký khóa học</h2><p>{scopedEnrollments.length} lượt đăng ký • {branch==='all'?'Tất cả':branch}</p></div><button className="primary" onClick={()=>setShowEnrollment(true)}><Plus size={15}/> Đăng ký học</button></div><EnrollmentTable enrollments={scopedEnrollments} payments={payments}/></section>}
 {page==='payments'&&<section className="panel"><div className="panel-head"><div><h2>Phiếu thu học phí</h2><p>{scopedPayments.length} giao dịch • {branch==='all'?'Tất cả':branch}</p></div><button className="primary" onClick={()=>setShowPayment(true)}><Plus size={15}/> Ghi nhận thu tiền</button></div><div className="table-wrap"><table><thead><tr><th>Ngày thu</th><th>Học viên</th><th>Lớp</th><th>Số tiền</th><th>Phương thức</th><th>Mã giao dịch</th><th>Ghi chú</th></tr></thead><tbody>{scopedPayments.map(p=>{const e=enrollments.find(x=>x.id===p.enrollment_id);return <tr key={p.id}><td>{new Date(p.paid_at).toLocaleString('vi-VN')}</td><td>{e?.student?.full_name||'—'}</td><td>{e?.class?.name||'—'}</td><td><b>{money(p.amount)}</b></td><td>{methodLabel[p.method]||p.method}</td><td>{p.reference||'—'}</td><td>{p.note||'—'}</td></tr>})}</tbody></table></div></section>}
 </main>{showClass&&<ClassModal onClose={()=>setShowClass(false)} onSaved={load}/>} {showStudent&&<StudentModal student={editingStudent} canEdit={['admin','director'].includes(profile?.role)} onClose={()=>{setShowStudent(false);setEditingStudent(null)}} onSaved={load}/>} {showEnrollment&&<EnrollmentModal students={students} classes={classes} onClose={()=>setShowEnrollment(false)} onSaved={load}/>} {showPayment&&<PaymentModal enrollments={enrollments} payments={payments} onClose={()=>setShowPayment(false)} onSaved={load}/>}</div>
}
function Login(){return <div className="login"><div className="login-card"><div className="logo big">LH</div><h1>Thu học phí</h1><p>Phiên đăng nhập CRM không còn hoạt động.</p><button className="primary full" onClick={()=>window.location.href=window.location.pathname}>Quay lại CRM</button></div></div>}
function AccessDenied(){return <div className="login"><div className="login-card"><div className="logo big">LH</div><h1>Thu học phí</h1><p>Tài khoản Sale chưa có quyền quản trị thu học phí.</p><button className="primary full" onClick={()=>window.location.href=window.location.pathname}>Quay lại CRM</button></div></div>}
function Card({label,value,note,icon}:{label:string;value:string;note:string;icon:React.ReactNode}){return <div className="card"><div className="card-icon">{icon}</div><div className="label">{label}</div><div className="value">{value}</div><div className="note">{note}</div></div>}
function EnrollmentTable({enrollments,payments}:{enrollments:Enrollment[];payments:Payment[]}){return <div className="table-wrap"><table><thead><tr><th>Học viên</th><th>Lớp</th><th>Cơ sở</th><th>Giá gốc</th><th>Giảm</th><th>Phải thu</th><th>Đã thu</th><th>Còn nợ</th></tr></thead><tbody>{enrollments.map(e=>{const paid=payments.filter(p=>p.enrollment_id===e.id).reduce((a,p)=>a+Number(p.amount),0);return <tr key={e.id}><td><b>{e.student?.full_name||'—'}</b><small>{e.student?.phone||'—'}</small></td><td>{e.class?.name||'—'}</td><td>{e.class?.branch||e.student?.branch||'—'}</td><td>{money(e.list_price)}</td><td>{money(e.discount_amount)}</td><td>{money(e.final_price)}</td><td>{money(paid)}</td><td>{money(Math.max(0,Number(e.final_price)-paid))}</td></tr>})}</tbody></table></div>}
function ClassModal({onClose,onSaved}:{onClose:()=>void;onSaved:()=>void}){async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;const f=new FormData(e.currentTarget);const {error}=await supabase.from('classes').insert({name:f.get('name'),course:f.get('course')||null,branch:f.get('branch'),teacher_name:f.get('teacher_name')||null,start_date:f.get('start_date')||null,end_date:f.get('end_date')||null,total_sessions:Number(f.get('total_sessions')||0)||null,list_tuition:Number(f.get('list_tuition')||0),status:f.get('status')});if(error)alert(error.message);else{onClose();onSaved()}}return <Modal title="Thêm lớp học" onClose={onClose}><form onSubmit={submit}><input name="name" required placeholder="Tên lớp, ví dụ: Giao tiếp Trung cơ bản K10"/><select name="course" defaultValue=""><option value="">Chọn khóa học</option><option value="HSK 1">HSK 1</option><option value="HSK 2">HSK 2</option><option value="HSK 3">HSK 3</option><option value="HSK 4">HSK 4</option><option value="HSK 5">HSK 5</option><option value="HSK 6">HSK 6</option><option value="HSK 7">HSK 7</option><option value="HSK 8">HSK 8</option><option value="HSK 9">HSK 9</option><option value="HSK 1–3">HSK 1–3</option><option value="HSK 1–4">HSK 1–4</option><option value="HSK 1–6">HSK 1–6</option><option value="HSK 1–9">HSK 1–9</option><option value="Giao tiếp Cơ bản">Giao tiếp Cơ bản</option><option value="Giao tiếp Trung cấp / Thực chiến">Giao tiếp Trung cấp / Thực chiến</option><option value="Giao tiếp Nâng cao / Thương mại">Giao tiếp Nâng cao / Thương mại</option><option value="Combo Cơ bản → Nâng cao">Combo Cơ bản → Nâng cao</option></select><select name="branch"><option>Bắc Ninh</option><option>Lạng Sơn</option></select><input name="teacher_name" placeholder="Tên giảng viên"/><div className="form-grid"><label>Ngày bắt đầu<input name="start_date" type="date"/></label><label>Ngày kết thúc<input name="end_date" type="date"/></label></div><div className="form-grid"><input name="total_sessions" type="number" placeholder="Số buổi"/><input name="list_tuition" type="number" placeholder="Học phí niêm yết"/></div><select name="status"><option value="planned">Dự kiến</option><option value="active">Đang học</option><option value="completed">Đã kết thúc</option><option value="cancelled">Đã hủy</option></select><div className="modal-actions"><button type="button" onClick={onClose}>Hủy</button><button className="primary">Lưu lớp</button></div></form></Modal>}
function StudentModal({student,canEdit,onClose,onSaved}:{student:Student|null;canEdit:boolean;onClose:()=>void;onSaved:()=>void}){async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;const f=new FormData(e.currentTarget);const payload={full_name:String(f.get('full_name')||'').trim(),phone:f.get('phone')||null,email:f.get('email')||null,branch:f.get('branch')};const result=student&&canEdit?await supabase.from('students').update(payload).eq('id',student.id):await supabase.from('students').insert(payload);if(result.error)alert(result.error.message);else{onClose();onSaved()}}return <Modal title={student?'Sửa thông tin học viên':'Thêm học viên'} onClose={onClose}><form onSubmit={submit}><input name="full_name" required defaultValue={student?.full_name||''} placeholder="Họ và tên"/><input name="phone" defaultValue={student?.phone||''} placeholder="Số điện thoại"/><input name="email" type="email" defaultValue={student?.email||''} placeholder="Email"/><select name="branch" defaultValue={student?.branch||'Bắc Ninh'}><option>Bắc Ninh</option><option>Lạng Sơn</option></select><div className="modal-actions"><button type="button" onClick={onClose}>Hủy</button><button className="primary">{student?'Lưu thay đổi':'Lưu học viên'}</button></div></form></Modal>}
function EnrollmentModal({students,classes,onClose,onSaved}:{students:Student[];classes:ClassRow[];onClose:()=>void;onSaved:()=>void}){const [classId,setClassId]=useState('');const selected=classes.find(c=>c.id===classId);const [discount,setDiscount]=useState('0');const [discountType,setDiscountType]=useState<'vnd'|'percent'>('vnd');const list=Number(selected?.list_tuition||0);const discountValue=Number(discount||0);const discountAmount=discountType==='percent'?Math.min(list,list*discountValue/100):Math.min(list,discountValue);const final=Math.max(0,list-discountAmount);async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase||!selected)return;const f=new FormData(e.currentTarget);const {error}=await supabase.from('enrollments').insert({student_id:f.get('student_id'),class_id:classId,list_price:list,discount_amount:discountAmount,discount_type:discountType,discount_percent:discountType==='percent'?discountValue:0,final_price:final,status:'active',note:f.get('note')||null});if(error)alert(error.message);else{onClose();onSaved()}}return <Modal title="Đăng ký học viên vào lớp" onClose={onClose}><form onSubmit={submit}><select name="student_id" required><option value="">Chọn học viên</option>{students.map(s=><option key={s.id} value={s.id}>{s.full_name} • {s.phone||'—'} • {s.branch||'—'}</option>)}</select><select value={classId} onChange={e=>setClassId(e.target.value)} required><option value="">Chọn lớp</option>{classes.filter(c=>c.status!=='cancelled').map(c=><option key={c.id} value={c.id}>{c.name} • {c.branch} • {money(c.list_tuition)}</option>)}</select><div className="form-grid"><label>Giá niêm yết<input value={money(list)} readOnly/></label><label>Hình thức giảm<select value={discountType} onChange={e=>setDiscountType(e.target.value as 'vnd'|'percent')}><option value="vnd">Giảm theo VNĐ</option><option value="percent">Giảm theo %</option></select></label></div><div className="form-grid"><label>{discountType==='percent'?'Mức giảm (%)':'Mức giảm (VNĐ)'}<input type="number" min="0" max={discountType==='percent'?100:list} value={discount} onChange={e=>setDiscount(e.target.value)}/></label><label>Tiền giảm<input value={money(discountAmount)} readOnly/></label></div><label>Học phí phải thu<input value={final} readOnly/></label><textarea name="note" placeholder="Ghi chú giảm giá / chính sách"></textarea><div className="modal-actions"><button type="button" onClick={onClose}>Hủy</button><button className="primary" disabled={!classId}>Lưu đăng ký</button></div></form></Modal>}
function PaymentModal({enrollments,payments,onClose,onSaved}:{enrollments:Enrollment[];payments:Payment[];onClose:()=>void;onSaved:()=>void}){const [enrollmentId,setEnrollmentId]=useState('');const selected=enrollments.find(e=>e.id===enrollmentId);const paid=selected?payments.filter(p=>p.enrollment_id===selected.id).reduce((a,p)=>a+Number(p.amount),0):0;const debt=selected?Math.max(0,Number(selected.final_price)-paid):0;async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase||!selected)return;const f=new FormData(e.currentTarget);const amount=Number(f.get('amount')||0);if(amount<=0||amount>debt){alert(`Số tiền thu phải lớn hơn 0 và không vượt công nợ ${money(debt)}.`);return}const raw=String(f.get('paid_at')||'');const {data:user}=await supabase.auth.getUser();const {error}=await supabase.from('payments').insert({enrollment_id:enrollmentId,amount,paid_at:raw?new Date(raw).toISOString():new Date().toISOString(),method:f.get('method'),reference:f.get('reference')||null,note:f.get('note')||null,received_by:user.user?.id||null});if(error)alert(error.message);else{onClose();onSaved()}}return <Modal title="Ghi nhận thu học phí" onClose={onClose}><form onSubmit={submit}><select value={enrollmentId} onChange={e=>setEnrollmentId(e.target.value)} required><option value="">Chọn học viên / lớp</option>{enrollments.filter(e=>e.status!=='cancelled').map(e=>{const p=payments.filter(x=>x.enrollment_id===e.id).reduce((a,x)=>a+Number(x.amount),0);return <option key={e.id} value={e.id}>{e.student?.full_name} • {e.class?.name} • Còn {money(Math.max(0,Number(e.final_price)-p))}</option>})}</select>{selected&&<div className="demo-note">Phải thu: <b>{money(selected.final_price)}</b> • Đã thu: <b>{money(paid)}</b> • Còn nợ: <b>{money(debt)}</b></div>}<input name="amount" type="number" min="1" max={debt||undefined} required placeholder="Số tiền thu"/><input name="paid_at" type="datetime-local" defaultValue={new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16)}/><select name="method"><option value="bank_transfer">Chuyển khoản</option><option value="qr">QR</option><option value="cash">Tiền mặt</option><option value="card">Thẻ</option><option value="other">Khác</option></select><input name="reference" placeholder="Mã giao dịch / nội dung chuyển khoản"/><textarea name="note" placeholder="Ghi chú"></textarea><div className="modal-actions"><button type="button" onClick={onClose}>Hủy</button><button className="primary" disabled={!selected||debt<=0}>Lưu phiếu thu</button></div></form></Modal>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="modal-backdrop"><div className="modal"><div className="modal-title"><div><h2>{title}</h2></div><button className="close-btn" onClick={onClose}><X size={15}/></button></div>{children}</div></div>}
createRoot(document.getElementById('root')!).render(<App/>);
